### ISSUE TITLE
role of /design folder

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#101]
Hey,

I am confused about the /design folder. Looks a bit like a prototyping artifact. If so, why not remove it?

If this contains example code - would it not be better to transform these into test cases right away? Would be good to agree on a clean way of contributing test cases so that we can start building up a nice library of sas/stata/other mmrm package results to compare against and demonstrate the functionality of the package.

**Comment by BrianLang** [comment]
It's for design docs. If we want to collaboratively work through a given issue, we can write literate code to explore the various steps and solicit feedback. 
Example issues would be those that start with "design". 
These artifacts provide short term documentation of work prior to creation of the functions, documentation, and testing. 

What do you think?

**Comment by danielinteractive** [comment]
Hi @kkmann , so this folder is not part of the R package (it is ignored for the build). It is part of the development process for large scale features. It gives us a space to share "design docs" as @BrianLang described as part of the same repository. It has served us well so far on many different projects.
We will describe this in the developer guide.

**Comment by kkmann** [comment]
I think this will be addressed as part of  #103
