### ISSUE TITLE
Summarize package scope, reference introduction vignette in README

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#102]
Background: the README is important to give the first time user a quick start into the package.

To do:

- [ ] Add the package scope within the very first section of the README, i.e. just after "The mmrm package implements mixed models for repeated measures (MMRM) in R based on Template Model Builder (TMB).", e.g. bullet list with:
	- [ ] response: normally distributed
	- [ ] covariance structures: unstructured, Toeplitz, AR1, compound symmetry
	- [ ] groups: either single covariance structure for all subjects, or separate by grouping variable
	- [ ] variances: homogeneous or heterogeneous between time points
	- [ ] least square means: `emmeans` package can be used with outputs to obtain least square means
	- [ ] degrees of freedom: Satterthwaite adjustment (planned is to add Kenward-Roger adjustment as alternative)
	- [ ] and others, please see through vignettes for major features
- [ ] Reference the introduction vignette under "Details", next to the other two vignette references.

**Comment by BrianLang** [comment]
"and others, please see through vignettes for major features" should this be included verbatim, or should I go through the vignettes to allow myself to add to this list? 

Weary of making another long list of all of the functionality, what do you think?

**Comment by danielinteractive** [comment]
@BrianLang yeah here I thought to just scan the vignettes for other major features and then include those in the bullet list too (basically just to check what is missing above)

**Comment by danielinteractive** [comment]
@BrianLang please tick off the boxes in the task as you completed them , thanks
