### ISSUE TITLE
Use Hessian for `nlminb()`

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#104]
To do:

- [x] Improve the algorithm vignette details
- [x] Let's use the Hessian for `nlminb()`
	- [ ] maybe we need a flag to decide whether optimization function takes the `hessian` argument?
	- [ ] add tests specifically for `nlminb()` use

Original:

Hey,

the docs state 

https://github.com/openpharma/mmrm/blob/e6262cb35ad733aa5d45b0e853e666bffc3f74d4/vignettes/algorithm.Rmd#L167

However, looking at the code 

https://github.com/openpharma/mmrm/blob/e6262cb35ad733aa5d45b0e853e666bffc3f74d4/R/tmb.R#L443-L453

and 

https://github.com/openpharma/mmrm/blob/e6262cb35ad733aa5d45b0e853e666bffc3f74d4/R/fit.R#L23-L28

it would see that we only use gradient information (not Hessian!) and quasi Newton methods (Newton-Raphson for minimization would use exact Hession). Is that correct? I guess the Hessian comes into play for the standard errors?

**Comment by danielinteractive** [comment]
Interesting, thx @kkmann . So I think for `nlminb()` we could supply the Hessian (which we currently don't do yet) and it would use it. Going through `optim()` which we do by default because so far it just works better does not use the Hessian indeed.
