### ISSUE TITLE
Add a test case where scales are leading to convergence problems

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#109]
To do:

- [x] come up with extreme scaling case, e.g. one coefficient OLS estimate should be 100000, other one should be very low e.g. 10^-5, variance very large -> does it work?
- [x] if yes -> add as a test case, done.
- [ ] if no -> let's have a look

**Comment by kkmann** [comment]
Just to clarify a bit on the issue. Many solvers tend to assume that the objective and the parameters are on a somewhat "reasonable" scale (e.g. changing a parameter by 1 changes the loglikelihood by 1). In cases where this is grossly violated local optimizers can terminate prematurely. This is documented in `optim` with the control parameters `fnscale` and `parscale` https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/optim. We should probably explore if/when this becomes a problem via extreme test cases. The obvious solution is to reparameterize models such that the parameters are roughly on the same scale.

**Comment by danielinteractive** [comment]
@kkmann feel free to edit the description directly

**Comment by kkmann** [comment]
@danielinteractive check out #119 seems that this is not an issue at all in the simple case that I constructed.I would close this an only address it again if we encounter a problem in a real application.

**Comment by danielinteractive** [comment]
Hi @kkmann , thanks for working on this - minor workflow issue is that @danleibovitz already had self-assigned this task before, did you check with him before?
otherwise @danleibovitz if you have something can you merge it into the same branch?

**Comment by danielinteractive** [comment]
@danleibovitz any additions from your side on the tests etc.?
