### ISSUE TITLE
Improve handling of `visits_zero_inds` and `coordinates`

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#110]
Current situation:
- for non-spatial covariance matrix, `visits_zero_inds` is used (integer vector) when subsetting the overall covariance matrix, see https://github.com/openpharma/mmrm/blob/c1e47d0e75d5b5cbe9e2fbc5df7eb811be677c1b/src/mmrm.cpp#L82
- for spatial covariance matrix, `coordinates` is used (numeric matrix), see https://github.com/openpharma/mmrm/blob/c1e47d0e75d5b5cbe9e2fbc5df7eb811be677c1b/src/mmrm.cpp#L94

The question is whether this can be improved so that we e.g. put the `visits_zero_inds` in `coordinates` with a single column or something similar.

**Comment by kkmann** [comment]
Erm, I am afraid I would need more details on this. Is the idea to represent non-spatial covariance structures with respect to numeric coordinates as well but then a discrete distance metric like `round(|t1 - t2|)`? I am all for abstraction and unification but in this case it might actually make sense to keep the implementations separate.

**Comment by danielinteractive** [comment]
@kkmann no worries this is actually not a  CRAN milestone issue :-) 
I tried to clarify the description.
