### ISSUE TITLE
mmrm vs mmrm_tmb abstraction

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#113]
Hey,

I am struggling a bit with understanding the use of the ` mmrm` vs `mmrm_tmb` identifiers in the package. 

Assuming that the main entry point to the package is `mmrm()`, the fit is dispatched to `fit_single_optimizer()` and thus eventually to `h_mmrm_tmb()`. This means that there is currently no need to differentiate between an mmrm and an mmrm_tmb fit since all fits are done using TMB. I see that this would potentially allow to switch fitting engines later but 

1. how realistic is this in the foreseeable future?
2. is it worth to maintain that additional abstraction layer if there is only one implementation of the fitting process?
3. currently, there is no way of specifying control parameters in the main function `mmrm()` - either we scratch `mmrm_tmb` or we allow passing an `mmrm_control` object (abstract superclass of `mmrm_tmb_control`?)

Would be good to align on whether we maintain the abstraction on fitting (potentially allowing non-tmb backends) or whether we can simplify this throughout the package.

**Comment by danielinteractive** [comment]
Hi @kkmann ,

thanks for the discussion contribution! 

Maybe the wording is confusing you a bit here - the main purpose of this layering is 
1) keeping functions small enough and 
2) having a "low-level" fitting function (currently called `h_mmrm_tmb()`) vs. the "high-level" fitting function `mmrm()` - which does the fit but then has the additional refitting functionality in case of non-convergence, plus is preparing the Jacobian which is needed for downstream Satterthwaite functionality.

For point 2), this is analogous to `lm.fit()` vs. `lm()` in the `stats` package. We have already applications for the low-level fitting (e.g. with `rbmi`) upcoming.

So bottomline: it does not really matter that we call it `_tmb`, we could also differentiate the low-level nature via different naming.

For the idea on passing `mmrm_control` to `mmrm()` - that could be nice, however will complicate the refitting logic I think. Would be a separate issue then to explore if it seems needed. Idea again is that for high-level interface the user won't go into those details.
