### ISSUE TITLE
Add a test for emmeans from weighted MMRM

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#117]
This is just to be sure we are not missing anything for weighted MMRMs there.

To do:

- [x] Add a new test to `test-emmeans.R`
  - [x] use a weighted MMRM
  - [x] run same analysis with SAS
  - [x] see that we match results up to numerical precision
- [x] Avoid any rounding in this file of results before comparing them to expectations
  - [x] if tolerance is too strict then reduce that slightly, e.g. `1e-3`

**Comment by danielinteractive** [comment]
@danleibovitz how is it going with this? can you maybe push a draft PR?

**Comment by danleibovitz** [comment]
Hey @danielinteractive, I'm dealing with some version issues on my local machine (some kind of mismatch in requirements between the latest R, TMB, and emmeans) and CMD checks are failing. I'm currently trying to sort that out, so I'm going to unassign myself from this for now.

**Comment by danielinteractive** [comment]
@danleibovitz ok you might want to try to install latest TMB and emmeans freshly from CRAN and then try again... also you need Rtools etc. but I guess you have that?
and do you have some code that you can push to a draft PR nevertheless? because then I could continue from there

**Comment by danleibovitz** [comment]
> @danleibovitz ok you might want to try to install latest TMB and emmeans freshly from CRAN and then try again... also you need Rtools etc. but I guess you have that? and do you have some code that you can push to a draft PR nevertheless? because then I could continue from there

Hi Daniel -- sorry for taking on an issue too early _again_. When CMD CHECK runs smoothly and when I have time, I'll take an issue from start to finish. Thanks for picking this one up.
