### ISSUE TITLE
Try to reduce size of shared library

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#124]
Background: Currently we have a large shared library object from compiling the whole TMB into our package. This might cause problems for CRAN submission.

To do:
- [x] check current size of shared library - does it cause CRAN note during `R CMD check --as-cran`?
	- 133.8 MB currently. seems too big
	- `checking installed package size ... NOTE: installed size is 131.9Mb`
- [ ] is the idea in https://github.com/boennecd/survTMB/blob/master/src/_tmb.cpp feasible for our package?  They only precompile / include the necessary functions they need.
	- [ ] or not because we need too many functions?
	- [x] not tried yet, seems to complicated
- [x] other idea: avoid precompilation
	- [x] as explained here: https://rdrr.io/cran/TMB/man/precompile.html precompilation increases size of the binary
	- [x] we can get down to 73 Mb
	- [ ] however, `glmmTMB` only has 14 Mb ... see https://www.r-project.org/nosvn/R.check/r-release-windows-x86_64/glmmTMB-00check.html
- [x] check with TMB team on other possibilities to reduce size
	- [x] https://github.com/kaskr/adcomp/issues/369

**Comment by kkmann** [comment]
Interesting, never did anything like that. Just for reference, packages using rstantools to ship precompiled stan models can easily exceed 50 Mb for the shared library.

**Comment by clarkliming** [comment]
I wonder if we can release the package without compilation at all? just send the source code there and let the user compile & install?

**Comment by danielinteractive** [comment]
@clarkliming CRAN always compiles packages (fortunately for users)

**Comment by danielinteractive** [comment]
@clarkliming no we don't want that, we want to have the compiled code on CRAN such that users don't need to do that. especially for this package because 1) they need RTools on Windows 2) compilation takes too long
