### ISSUE TITLE
Last steps before CRAN submission

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#126]
To do:

- [x] Resolve `C++ One Definition Rule` - see below - cannot reproduce this
	- [x] I suspect that we should merge https://github.com/openpharma/mmrm/blob/main/src/test-runner.cpp into https://github.com/openpharma/mmrm/blob/main/src/init.h to avoid duplicate definition of `run_testthat_tests` -> does not work
- [x] Disable parallel runs when on CRAN checks
	- [x] I guess the easiest is to modify the `free_cores()` logic such that when on CRAN checks it always returns 1
- [x] Confirm authors
	- [x] Craig -> ctb
	- [x] Alessandro -> removed
	- [x] @kkmann -> author
	- [x] alphabetical order within authors
- [x] remove author names from vignettes to simplify maintenance
- [x] Increment `TMB` version required to `1.9.1` (latest on CRAN)
- [x] Confirm that `R CMD check --as-cran` passes flawlessly
- [x] Increment version to 0.1.2
	- [x] make sure to add [skip vbump] to any commit messages
- [x] Check `NEWS`
- [x] submit to R-Hub to repeat checks on other platforms
	- [x] see https://builder.r-hub.io/about.html

**Comment by pawelru** [comment]
When running R CMD CHECK on one of our internal systems I got following warning:
```
* checking whether package ‘mmrm’ can be installed ... WARNING
Found the following significant warnings:
  init.h:11:13: warning: ‘run_testthat_tests’ violates the C++ One Definition Rule  [-Wodr]
See ‘/tmp/ansible._opQOYbuild/install_rpkgs_with_log/buildfiles/check/mmrm.Rcheck/00install.out’ for details.
```

It might be good to resolve it before CRAN submission

**Comment by danielinteractive** [comment]
Interesting thanks @pawelru - did not see that yet

**Comment by danielinteractive** [comment]
@pawelru if you still have it, can you maybe send me the log file (`/tmp/ansible._opQOYbuild/install_rpkgs_with_log/buildfiles/check/mmrm.Rcheck/00install.out`) ? I am having a hard time to reproduce this :-) thx

**Comment by pawelru** [comment]
This file is 4k+ lines long but I think it's this part:
```
init.h:11:13: warning: ‘run_testthat_tests’ violates the C++ One Definition Rule  [-Wodr]
 extern SEXP run_testthat_tests();
             ^
/opt/bee/share/nest-packages/2022_10_13/4.1.1/libs/testthat/include/testthat/testthat.h:165:17: note: type mismatch in parameter 1
 extern "C" SEXP run_testthat_tests(SEXP use_xml_sxp) {
                 ^
/opt/bee/share/nest-packages/2022_10_13/4.1.1/libs/testthat/include/testthat/testthat.h:165:17: note: type ‘struct SEXPREC *’ should match type ‘void’
/opt/bee/share/nest-packages/2022_10_13/4.1.1/libs/testthat/include/testthat/testthat.h:165:17: note: ‘run_testthat_tests’ was previously declared here
/usr/bin/nm: /tmp/ansible.CJ24uwbuild/install_rpkgs_with_log/buildfiles/check/mmrm.Rcheck/00_pkg_src/mmrm/src/mmrm.o: plugin needed to handle lto object
/usr/bin/nm: /tmp/ansible.CJ24uwbuild/install_rpkgs_with_log/buildfiles/check/mmrm.Rcheck/00_pkg_src/mmrm/src/test-runner.o: plugin needed to handle lto object
installing to /tmp/ansible.CJ24uwbuild/install_rpkgs_with_log/buildfiles/check/mmrm.Rcheck/00LOCK-mmrm/00new/mmrm/libs
```

**Comment by danielinteractive** [comment]
Thanks Pawel, fortunately on CRAN pretest this did not come up ...

**Comment by danielinteractive** [comment]
I think https://github.com/openpharma/mmrm/pull/139 fixes it
