### ISSUE TITLE
Try to reproduce error and fix the cause

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#129]
Error: was observed in downstream `tern.mmrm` test
![image](https://user-images.githubusercontent.com/1071227/195793016-05f2757c-596b-4540-bb60-902fbd349660.png)

Reprex:
```r
small_dat <- data.frame(
    FEV1 = c(1, 2, 3, 4, 5, 6),
    AVISIT = factor(c("V1", "V1", "V2", "V3", "V3", "V4")),
    USUBJID = c("A", "B", "A", "C", "D", "A")
  )
  vars <- list(
    response = "FEV1",
    id = "USUBJID",
    visit = "AVISIT"
  )
  fit <- mmrm::mmrm(
    formula = FEV1 ~ AVISIT + ar1(AVISIT | USUBJID),
    data = small_dat
  )
```

Problem: I cannot reproduce this error locally.

To do:
- [x] try to reproduce locally -> @BrianLang could reproduce it!
- [x] if locally cannot reproduce, use docker image http://ghcr.io/insightsengineering/rstudio_4.2.1_bioc_3.15 and try to reproduce there -> not reproducible
- [x] debug where it is coming from
- [x] add unit test
- [x] fix:
	- [x] `h_summarize_all_fits`: also include errors
	- [x] `fit_single_optimizer`: selectively exclude convergence failures from `stop()` since these should be included as `errors` in return struct
	- [x] `h_mmrm_tmb_assert_opt`: 
		- [x] always fail if convergence problems, don't just give warnings (it is an assertion function)
		- [x] use the same eigen threshold as `solve()` does or just directly use `solve()` since that is what is needed in the fit function next
- [x] new approach is needed, because we rely on the fact that `fit_single_optimizer` returns an `mmrm_fit` object even in the case of non-convergence - and it seems too much change now to throw this over.
	- [x] refactor `h_mmrm_tmb_assert_opt` into `h_mmrm_tmb_check_conv` which will be used after doing the `h_mmrm_tmb_fit`
	- [x] catch the `solve` error in `h_mmrm_tmb_fit`
	- [x] remove again the error handling stuff from before since now it will just be warnings

**Comment by danielinteractive** [comment]
@gowerc is helping me currently with this

**Comment by BrianLang** [comment]
Great news! I can reproduce on our (MSD) rstudio server. 

```r
> library(mmrm)
> small_dat <- data.frame(
+     FEV1 = c(1, 2, 3, 4, 5, 6),
+     AVISIT = factor(c("V1", "V1", "V2", "V3", "V3", "V4")),
+     USUBJID = c("A", "B", "A", "C", "D", "A")
+ )
> vars <- list(
+     response = "FEV1",
+     id = "USUBJID",
+     visit = "AVISIT"
+ )
> fit <- mmrm::mmrm(
+     formula = FEV1 ~ AVISIT + ar1(AVISIT | USUBJID),
+     data = small_dat
+ )
Error in FUN(X[[i]], ...) : 
  system is computationally singular: reciprocal condition number = 1.24406e-16
```

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.9 (Maipo)

Matrix products: default
BLAS/LAPACK: /data/app/Rtoolkit-EIM/1.2.0/lib/libopenblas_nehalemp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mmrm_0.1.0.9017

loaded via a namespace (and not attached):
 [1] mvtnorm_1.1-3       lattice_0.20-45     rbibutils_2.2.9     grid_4.2.1          xtable_1.8-4        lifecycle_1.0.3     nlme_3.1-157       
 [8] backports_1.4.1     magrittr_2.0.3      estimability_1.4.1  Rdpack_2.4          rlang_1.0.6         stringi_1.7.8       cli_3.4.1          
[15] rstudioapi_0.14     Matrix_1.4-1        checkmate_2.1.0     tools_4.2.1         TMB_1.9.1           stringr_1.4.1       emmeans_1.8.1-1    
[22] numDeriv_2016.8-1.1 parallel_4.2.1      compiler_4.2.1     
```

**Comment by BrianLang** [comment]
The error happens in `refit_multiple_optimizers` when convergence isn't reached. 

In particular it happens when pass the `optimizers` to `fit_single_optimzier` with `mclapply`. 

```r
all_fits <- suppressWarnings(parallel::mclapply(X = optimizers, 
    FUN = fit_single_optimizer, formula = old_formula, data = old_data, 
    weights = old_weights, reml = fit$reml, start = fit$theta_est, 
    accept_singular = accept_singular, mc.cores = n_cores_used, 
    mc.silent = TRUE))
```

**Comment by danielinteractive** [comment]
@BrianLang awesome - quick call?
