### ISSUE TITLE
Deprecate `free_cores()`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#146]
Note that this might likely also lead to improvements of the function itself.

To do:

- [ ] Evaluate https://cran.r-project.org/web/packages/parallelly/index.html in particular its function `freeCores()`
- [ ] if that looks ok we can just drop our `free_cores()` from this package completely
- [ ] which means to first deprecate it and later remove it
- [ ] in which case just need to refactor downstream dependencies `tern.mmrm` and `teal.modules.clinical`

**Comment by kkmann** [comment]
Hm, interesting. Any point inswitching to futures? Probably not , so far there are no convergence issues that would require optimizer restarts and as long as there are only a handful of reruns there is no need for the flexibility of futures + we avoid adding a dependency.

**Comment by kkmann** [comment]
Another approach would be to set the cores to 1 by default and let the user figure out how many cores to use. Could point towards freeCores() or detectCores() in the docs. Also makes sense since this is not really a problem to be solved by mmrm.

**Comment by danielinteractive** [comment]
@kkmann yeah this is what we are actually doing right now - default to 1 and point users. This issue is about then going one step further and removing the free cores function from the package

**Comment by kkmann** [comment]
ok, +1 for just removing it then

**Comment by kkmann** [comment]
Uha, the downstream deprecation is a bit too much for me.

**Comment by danielinteractive** [comment]
I can handle that bit, no worries

**Comment by kkmann** [comment]
#155
