### ISSUE TITLE
[placeholder] `mmrm` gives different convergence results when used inside parallel clusters sometimes

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#151]
Background:
- the package `rbmi` is using `mmrm` 
- it is parallelizing computations involving `mmrm::mmrm(..., n_cores = 1L)` (so this itself is not parallelized) using PSOCK clusters (so not the usual forking = `mclapply`)
- on some operating systems / configurations / machines, some of the unit tests are failing: parallelly computed results are not identical to sequentially computed results
- Daniel can reproduce this problem with `rbmi` on his old Windows computer
- we are currently trying to boil this down to a reprex for the `mmrm` package

**Comment by kkmann** [comment]
Hm, from your description it is not entirely clear to me whether this is a rbmi or mmrm problem. If mmrm is called in single-core mode that should not be an issue. Can we check whether we really capture all randomness corrrectly? Could it be related to optimizer starting parameters? I think we have deterministic inits tho.

This does not sound like a data set specific issue, so would be good to get a reprex. Essentially refitting the same mmrm multiple times to the same (?) data in parallel on a PSOCK cluster?

**Comment by danielinteractive** [comment]
Yeah the reprex is the problem actually. We were trying to at least rerun on the same machine on Friday and that time it did not show up at all. Therefore closing for now - it could well be a (memory?) problem that is well beyond our code base.
