### ISSUE TITLE
Good explanation of name + G/R side random effects

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#153]
If my understanding is correct, mmrm only supports so called marginal/population average models (no individual-level random effects). Do we already make this explicit to people comming from the linear mixed effects side of things the naming might otherwise be a bit confusing. @chstock maybe?

Some resources I found helpful on this topic. 

https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_glimmix_overview05.htm

https://thestatsgeek.com/2020/12/30/mixed-model-repeated-measures-mmrm-in-stata-sas-and-r/

**Comment by chstock** [comment]
...yes, that's the plan. @BrianLang and I discussed another vignette last week that reviews and comares (very generally) similar models and corresponding R/SAS implementations, including RS & I and GEE models.

**Comment by danielinteractive** [comment]
Sounds great thanks @chstock - I think that it is worth a dedicated vignette on that theoretical comparison topic

**Comment by danielinteractive** [comment]
So @chstock I guess you are working on this now, is that correct?
If yes please assign this issue to yourself (top right), then we avoid any duplicate work. thanks :-)

**Comment by danielinteractive** [comment]
@chstock Do you have any updates, or any questions? :-)

**Comment by chstock** [comment]
> @chstock Do you have any updates, or any questions? :-)
Not yet, to be honest. I know what I'd like to do and how, have struggled to find time yet though. Happy to discuss how to proceed.

**Comment by danielinteractive** [comment]
@chstock cool no worries - maybe it could be a good start to just put out a draft PR with an outline and your "bullet points" what you would like to have covered? then other folks might jump in and help you put meat to those bones

**Comment by chstock** [comment]
OK, will do!

**Comment by kkmann** [comment]
here's some more code: https://cjangelo.github.io/SPR/articles/a09_MMRM_Sim_Study.html

I wonder, with @BrianLang's PR #165 - would there still be room for a small practial stats paper/review on the MMRM model and implementation zoo? Might be better to spin this off of the `mmrm` package and focus on the technical side in the vignette/PR. Could reference the vignette from the manuscript.

**Comment by danielinteractive** [comment]
@kkmann My 2 cents would be to first finish the two vignettes (one practical, one theoretical overview) and then take all vignettes we have plus additional intro / literature review and condense that in a nice JSS or R Journal paper.
If in addition there is energy and time for another paper even better, but I would say let's first get the vignettes and the package paper done
