### ISSUE TITLE
Improve use of optimizers in general, incl. refitting, default choice, etc.

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#156]
Hi,

currently, we only refit using multiple optimizers if the default one fails to converge. Would it make sense to have another option besides "automatic" that fits all optimizers and assesses whether there is discrepancy beyond a certain tolerance? I am not worried about speed at all when it comes to refitting and anything that helps diagnosing unstable fits / numeric issues early is helpful.

https://github.com/openpharma/mmrm/blob/b0733e9f054601704d4b34ddce6e69d2ab524c9b/R/fit.R#L244

If so, how would we measure agreement between solutions? On the loglikelihood level? On the paramter level? Both?

**Comment by danielinteractive** [comment]
Use of optimizers has been improved recently with #188 . At this point I don't think we need to further go into the business of fitting the model with multiple optimizers from the start. So I would suggest to close, unless we have a strong case here?

**Comment by kkmann** [comment]
Agreed, let's not solve a potential problem that we have not seen in practice yet. We did some testing around stability of scaling and it did not seem to be an issue.
