### ISSUE TITLE
Some improvements to the documentation

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#157]
- [x] CRAN badge 
- [x] Cumulative CRAN downloads badge / monthly
- [x] ~lifecycle badge~ overlaps too much with repo status. Not the biggest fan of either but ok.
- [x] build/check status badge
- [ ] test coverage badge
- [x] link detailed info directly in the readme, no need to show code to build vignettes

**Comment by kkmann** [comment]
How do we get a test coverage badge for main? Could switch to codeov or covralls?

**Comment by danielinteractive** [comment]
@cicdguy any idea for the test coverage badge that @kkmann refers to ?

**Comment by kkmann** [comment]
@cicdguy the coverage badge does not display correclty yet for me but if I follow the link it displays the svg correctly - any ideas? Does it work for yo? https://raw.githubusercontent.com/openpharma/mmrm/_xml_coverage_reports/data/main/badge.svg

**Comment by kkmann** [comment]
sry, too impatient - working now, great and thx again!
![image](https://user-images.githubusercontent.com/2482236/199489249-771c472f-60cf-4708-9924-dcdb00afaf03.png)
