### ISSUE TITLE
Add function `fit_single_optimizer()`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#16]
To do:

- [x] See design document [here](https://github.com/openpharma/mmrm/blob/9da1d5ef01ec78b7cc030a2fce2c4edf18f961a3/design/design_fit.Rmd#L371)
- [x] Add function `fit_single_optimizer()` in file `R/fit.R`
	- [x] Modify the prototype such that also `nlminb` could be used
	- [x] Don't include `Nelder-Mead` as an option since that does not make use of the automatic differentation in `glmmTMB`
- [x] Add unit tests in file `testthat/test-fit.R`
  - [x] If needed please improve the function code
  - [x] for the `start` values you can use `list(theta = c(3, 0.5))` e.g. in the case of AR1 model
- [x] Add `roxygen2` documentation chunks
  - [x] Run Build > Document, Build > Load All, and check that documentation looks good
- [x] Add function name to `pkgdown.yaml`
- [x] Run Build > Check to ensure that checks pass

```r
fit_single_optimizer <- function(formula,
                                 data,
                                 start = NULL,
                                 optimizer = c("L-BFGS-B", "BFGS", "CG", "nlminb")) 
```

and then inside the function:

```r
control <- glmmTMB::glmmTMBControl(
    optimizer = if (optimizer == "nlminb") stats::nlminb else stats::optim,
    optArgs = if (optimizer == "nlminb") list() else list(method = optimizer),
    parallel = 1L
  )
```

**Comment by juliadedic1** [comment]
@danielinteractive no questions as of yet. Hoping to finish it up today. Thanks for checking in!

**Comment by juliadedic1** [comment]
@danielinteractive should this function be added to the "functions" section in the `pkgdown.yaml`? Also, I am not sure about the unit-tests I created for this one. I will push what I have and we can discuss tomorrow in our stand-up!

**Comment by danielinteractive** [comment]
@juliadedic1 yeah please add to the functions section, yes let's have a look tomorrow!
