### ISSUE TITLE
Check that Linux binary for `mmrm` on RSPM works as expected 

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#163]
To do:

- [ ] Probably we don't need to test Mac and Windows?
- [ ] Install Linux binary from https://packagemanager.rstudio.com/client/#/repos/1/packages/mmrm
- [ ] Run tests

**Comment by kkmann** [comment]
Hm, interesting point given that RSPM is becoming ever more popular. I gave it a try on Ubuntu 20.04 and it seems to work (see below).

I ran 
```
install.packages("mmrm", INSTALL_opts = "--install-tests")
install.packages("emmeans")
testInstalledPackage("mmrm")
```
against  `https://packagemanager.rstudio.com/all/__linux__/focal/latest`

![image](https://user-images.githubusercontent.com/2482236/199691756-0a7cd22f-dff4-4014-a292-273e148b15ba.png)
 
Question: Which binaries do you want to check, there are 3 versions of Ubuntu alone, CentOS etc. ... is that really something we want to get into? 
Question: If yes, we probably should run these on a matrix of platforms using GH actions and show the results somewhere. Would probably need containerized GH actions though to mimmic all these different distributions. Mac and Windows would be no problem though. 
Question: What is that emmeans output?

**Comment by danielinteractive** [comment]
thanks @kkmann for trying it out!
I think that is sufficient.
You would need the `emmeans` package to be installed to get the results.

**Comment by kkmann** [comment]
hey @danielinteractive just to make sure we are not overlooking unexpected behaviour: I do install emmeans and get this output running the tests. maybe there is some printing/cat not being captured? +1 for not being accountable for correct binaries for now.
