### ISSUE TITLE
create s3 method for {multilevelmod}

### ISSUE THREAD

**Issue by yonicd** [openpharma/mmrm#169]
Idea: Creating a method for tidymodels `multilevelmod::mmrm` to get broader audience of tidymodels users. There is already a method for *.gls engine so this addition would be pretty low hanging fruit.

Background material:
- https://multilevelmod.tidymodels.org/#available-engines
- https://github.com/tidymodels/multilevelmod/blob/a3d98fc8109590926e939d49c2b915325315a330/R/linear_reg_data.R#L391_L454

To do:
- [x] Understand how `multilevelmod` interfaces with `nlme::gls`, see background material
- [x] Prototype how it could interface with our `mmrm` function

**Comment by danielinteractive** [comment]
Thanks @yonicd that is a cool idea!
So I guess we will need to create a PR from a fork for https://github.com/tidymodels/multilevelmod.
Maybe we should check in with the maintainers first via an issue in their repo?

**Comment by yonicd** [comment]
We can prototype it on a branch here and see how the machinery works so the issue/PR is straight fw and an easy repex for them as maintainers to accept
