### ISSUE TITLE
Warn when visit levels are dropped / consider flag to include all levels

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#170]
To do:

- [x] add a warning when time point levels are dropped
- [x] a flag that allows to include all visit levels optionally 
  - [x] needs to go to `mmrm_control()`
- [x] modify https://github.com/openpharma/mmrm/blob/39eb47441e714fd6a584b8946a8d9341c96b754a/R/tmb.R#L268
  - [x] maybe only specifically drop levels of the visit? on the other hand, `lm()` also drops non-observed factor levels silently, see below
- [x] add tests
- [x] add `NEWS` entry

Would be good to be consistent with standard R behavior of other modeling functions. E.g. consider:
```r
df <- data.frame(y = c(0.1, 0.2), x = factor(c("a", "b"), levels = c("a", "b", "c")))
mod <- lm(y ~ x, data = df, singular.ok = FALSE)                 
mod
m <- model.frame(y ~ x, df)
str(m)
mm <- model.matrix(y ~ x, m)
mm
lm
```

Motivation:

mmrm models drop levels for visits, this is usually fine, but when a visit is dropped in all observations, the timepoint will be changed. e.g, if all subjects completes visit 1, 2 and 4, 3 is missed. Then it will be converted to 0, 1 and 2 in mmrm models. This changes the covariance matrix structure.

```r

df <- data.frame(
  usubjid = c("1", "1", "1"),
  visits = factor(c("1", "2", "4"), levels = as.character(1:4)),
  resp = rnorm(3)
)

fit <- mmrm(resp ~ ar1(visits|usubjid), data = df)


fit$tmb_data$visits_zero_inds  # get 0,1,2

fit$cov  # names are 1, 2 and 4

```

although we have  https://github.com/openpharma/mmrm/blob/88836158c2a71826ee98fbe997a80654ad961f49/tests/testthat/test-tmb.R#L1535

but it still seems not very reasonable.
e.g. a study has 4 scheduled visits, week 1, 2, 3 and 4. Due to some kind of lockdown, week3 data is not available. When users try to use "AR1", they assume that the correlation between each consecutive timepoint is the same. However, here in our model, the correlation between week 1 and 2 is the same as the correlation between 2 and 4.

I think we should at least provide a "Note" to let users know that their assumption might get violated?

**Comment by kkmann** [comment]
I was not aware of it and would expect a `warning` at least. The covariance structure should not be altered without raising something. I would be in favor of not dropping levels by default.

**Comment by danielinteractive** [comment]
@clarkliming it would be interesting how SAS is handling this? As additional input for decision.
I would also tend to make this more explicit.

**Comment by clarkliming** [comment]
in SAS there are no factors available (according to my knowledge at least) so you can not specify that there are four visits and one visit is missing for all observations. So if only week 1, 2 and 4 is available, then it is treated as visit 1, 2 3 respectively in SAS.

**Comment by clarkliming** [comment]
so basically I think we should be careful when dropping levels. dropping levels for usubjid is fine, for time points we should be careful

**Comment by danielinteractive** [comment]
Cool thanks @clarkliming . So then let's add a warning when time point levels are dropped
