### ISSUE TITLE
Avoid assignment of `weights` in environment as it can overwrite global environment variable

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#171]
there is a side effect that `weights` is assigned to the global environment. If this argument is used by the user, the "weights" in global environment can be changed accidentally.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1071227/201130298-c0285b1e-361e-4667-8443-0991314b70b6.png">

The reason is that https://github.com/openpharma/mmrm/blob/88836158c2a71826ee98fbe997a80654ad961f49/R/tmb.R#L258

Usually the formula's environment is "global env" so can cause issues.

I wonder if we should, instead of assigning weights to the environment, we should remove any environment of that formula?

To do:

- [x] Add unit test that reproduces overwriting of `weights` in global environment
- [x] Adapt code that this does not happen anymore
- [x] Make sure all tests pass
- [x] Add `NEWS` entry under Bug fixes

**Comment by clarkliming** [comment]
since we are requring the user specify formula and formula variables should all come from the dataset,  I think it is fine to use the "dataset" itself to replcase the formula environment?

**Comment by danielinteractive** [comment]
@clarkliming yes that could work

**Comment by danielinteractive** [comment]
@clarkliming are you not first finishing the KR stuff? :-)

**Comment by clarkliming** [comment]
> @clarkliming are you not first finishing the KR stuff? :-)

well, this is super fast and quick fix😆
