### ISSUE TITLE
Shall we cache the `lower_chol` for subjects so that it will not be re-calculated?

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#172]
currently, we derive the "lower_chol" for full visits, and for each subject that do not have full visits, we calculate their Cholesky based on the subset of the covariance matrix, and then we take the Cholesky decomposition again.

If there are subjects with the same missed visits (e.g., full visits is week 1, 2, 3 and 4, and some subjects only missed week 3, so their cholesky will computed multiple times (even though they are the same).

I wonder if we should use some kind of map to avoid repeated calculations?

**Comment by kkmann** [comment]
If we want to do that, it would probably be best to sort individuals by visit pattern at the start of the fit - then any internal function can assume a blocked structure by visit patterns  to benefit from it. Could spped things up quite a bit but then ... do we really have  a speed problem ;) ? I would happily err on the side of low-code-complexity when there is a trade-off with speed, at least until it becomes a problem.

**Comment by danielinteractive** [comment]
Agree that this is low priority. A map would work though and we do this in the KR calculations already.
