### ISSUE TITLE
implement KR1 method for covariance calculation/testing

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#180]
implement KR1 method

- [x] read through KR design doc
- [x] implement C++ side P,Q, R calculation
- [x] add support for weighting/groups
- [x] move sat/kr under mmrm
- [x] add argument in mmrm to conduct testing
- [x]  add unit testings
- [x] use fit as parameter for get_PQR(get_KR_component)
- [x] add integration tests compared with SAS
- [x] Add `NEWS` entry (under "New Features")
- [x] Adjust style for Roxygen documentation
	- [x] title style for titles, 
	- [x] blank lines for readability between sections
	- [x] parentheses for type with `\cr` afterwards
	- [x] At least one sentence description before arguments
- [x] add minimum assertions for inputs also for internal helper functions to make code defensive
- [x] make sure to keep lifecycle badges, and have them for new exported functions too.
- [x] prefix internal functions with `h_`
- [x] have unit tests for all functions (incl. internal, helper functions)

**Comment by danielinteractive** [comment]
Thanks @clarkliming , I would go for option 3, and we have C++ tests already to use as starting point

**Comment by danielinteractive** [comment]
@clarkliming please see here for additional things to check in the PR, thanks!
