### ISSUE TITLE
Add Option/Function for Relative Change Calculation?

### ISSUE THREAD

**Issue by changjosh92** [openpharma/mmrm#187]
**Summary**

Hi openpharma team,

Thanks so much for your work to optimize statistical summary generation! 
My request is to consider adding a relative change (increase/decrease) option to the package somehow.

Often times in clinical trials the question of how much better/worse did the intervention group perform relative to the control group can come up and it would be great to have this calculation operationalized in the package.

The difficulty in this calculation comes down to what defines better group performance for a given endpoint (e.g. higher magnitude is better/lower magnitude is better) and if the control group's model estimate demonstrated an increase or decrease in performance.

Below is a summary of prior work on how to best define and calculate the relative change between treatment groups (only 2 shown here):
![image](https://user-images.githubusercontent.com/93953459/205743250-c40a89c7-205f-4d7b-bd86-44e8ebcdc38c.png)

Right now the calculation would be done in R, but by pulling out each of the model estimates in a simple if-then condition.
Ultimately, this is a nice-to-have, but I think optimizing it for the package could drive adoption of the package much faster. I'm happy to be a resource with some prior code I've developed for TEAL apps based on `nlme` model outputs. Thanks!

**Comment by danielinteractive** [comment]
Moved to https://github.com/insightsengineering/tern.mmrm/issues/136
