### ISSUE TITLE
Add `predict()` method for `mmrm_tmb`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#189]
depends on #263

Motivation: 1) kind of a standard for models, 2) needed for support in the simulation framework [DHARMa](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA#integrating-a-package-with-dharma).

To do:

- [ ] Add a short design doc to work out the approach
- [ ] Add method
- [ ] Add tests
- [ ] Add to NEWS

**Comment by danielinteractive** [comment]
@kkmann I guess you are busy with our course :-) let us know if you need start help for this one

**Comment by danielinteractive** [comment]
Hi @kkmann do you think you can work on it this week?

**Comment by kkmann** [comment]
Mea culpa, blocked some time for it next week!

**Comment by kkmann** [comment]
@danielinteractive is there an interface for getting the covariance matrix of one or multiple individuals from a fitted mmrm object? It does not seem that any of the cov functionality is exposed to R at the moment. We would need that for prediction intervals. varcorr only seems to get a static matrix and is not enough for spatial covariance structures.

**Comment by kkmann** [comment]
I added a vignette with a draft description of what we would need to implement this. Again highlighting the connection to Gaussian Processes quite nicely x) #254 

@danielinteractive could you take a look at it to see whether my understanding is correct? 

For standard errors, we would also have to get the Jacobians via AD again - a bit beyond my understanding of the mmrm/tmb code basis. Is there anyone who could help?

**Comment by danielinteractive** [comment]
Thanks @kkmann , yeah we can help, either myself or maybe @clarkliming
