### ISSUE TITLE
Add `simulate()` method for `mmrm_tmb` (or `mmrm` if we need adjusted cov matrix of fixed effects)

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#190]
Motivation: 1) kind of a standard for models, 2) needed for support in the simulation framework [DHARMa](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA#integrating-a-package-with-dharma).

To do:

- [ ] Compare `?simulate` for the general semantics of this generic function for simulating from the predictive distribution
	- stats: simple
	- Ecfun: for `glm`s. Added `newdata` argument.
	- lme4: 
		- `simulate.formula`: which formula to use
		- `simulate.merMod`: simulate from fitted model.
- [ ] Continue prediction vignette by adding simulation section instead of separate design doc or vignette, because they refer to the same predictive distribution
- [ ] Add method
- [ ] Add tests
- [ ] Add to NEWS

**Comment by kkmann** [comment]
Great idea. Once thing that I would find extremely helpful in practice is being able to simulate from a model without fitting it first (trial simulation!). 

This would not require most of the TMB/fitting infrastructure in the first place but rather an alternative way of creating model objects from parameter specifications. Then it could use the `simulate()` infrastructure.

**Comment by danielinteractive** [comment]
@kkmann That would be yet another feature - this here would be to post-hoc work on a fitted object, to fit into the interface required by other packages, e.g. the mentioned DHARMa thing

**Comment by kkmann** [comment]
sure, just thinking what else we could do with it - just to clarify, this is simulating from the predictive distribution, not the parameters?

**Comment by danielinteractive** [comment]
Correct, predictive distribution - adding to description

**Comment by kkmann** [comment]
Great, tagging @mitchell-thomann and @zhuob in case they are interested.

**Comment by danielinteractive** [comment]
@ywang-gilead  Hi Ya let me know if you need any start help with this one

**Comment by danielinteractive** [comment]
Thanks @danleibovitz for taking this on! Please let me know how it goes and as soon as any questions or problems come up. Thanks!

**Comment by danielinteractive** [comment]
Hi @danleibovitz - hope all is well, let us know if you can work on this, otherwise we will need to reassign. Thanks a lot!

**Comment by kkmann** [comment]
hmhm, `simulate()` and `predict()` could use the same infrastructure - maybe let's first wrok together on `predict()` and keep 
 `simulate()` in mind. The only real difference is that we need the full conditional predictive variance covariance matrix, not just the diagonal.

**Comment by kkmann** [comment]
> Cool thanks a lot @danleibovitz ! Much appreciated.
> 
> Let's go with the simplest approach for now, i.e. `stats::simulate()` like. So you can do the next step now - short design doc to work out the approach. Already then make a draft PR for it.
> 
> Note that we don't have any random effects in `mmrm` so this should not play a role.

x) yeah still feel it is a 99% misnomer but here it makes our job a lot easier.

**Comment by danleibovitz** [comment]
I've pushed a simple version of the `simulate.mmrm()` method -- tests and design doc to follow. It currently only calls `fitted()`, but we can sub in `predict.mmrm()` when it's ready. 

Re. random effects -- I thought the idea might have been to add random effects capabilities eventually, as in [Cnaan, Laird and Slasor](https://doi.org/10.1002/(SICI)1097-0258(19971030)16:20%3C2349::AID-SIM667%3E3.0.CO;2-E)? But yes, our job is easy until then :)

**Comment by danielinteractive** [comment]
@danleibovitz Please start when you can on this one - thanks!

**Comment by danleibovitz** [comment]
@danielinteractive Yep, I've blocked some time today and tomorrow -- I'll ping you when it's ready for a review!

**Comment by danleibovitz** [comment]
@danielinteractive I think this is ready for a pull request, but I'd be happy to hear your feedback first. My primary concern is, is this where you imagined `simulate()` should be housed, i.e., in the `mmrm-methods.R` file?

**Comment by danielinteractive** [comment]
Thanks @danleibovitz , sounds great!! Thanks so much. Location wise it would probably go into `R/tmb-methods.R` close to `predict.mmrm_tmb`
