### ISSUE TITLE
Add `residuals()` method for `mmrm_tmb`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#191]
Motivation: 1) kind of a standard for models, 2) needed for support in the simulation framework [DHARMa](https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA#integrating-a-package-with-dharma).

To do:

- [ ] Add a short design doc to work out the approach
	- [ ] include raw and Pearson (standardized) residuals
	- [ ] think about optional "decorrelating" of residuals by multiplying with inverse Cholesky factor of covariance matrix
	- [ ] see `tern.mmrm` for starting points since we calculate the residuals there
- [ ] Add method
- [ ] Add tests
- [ ] Add to NEWS

**Comment by danjamstat** [comment]
@danielinteractive In case it's useful, I've added a residuals method to my fork - mostly based on the tern and nlme:::residuals.gls code

**Comment by danielinteractive** [comment]
Thank you @danjamstat ! Looks good - if you have time, can you make a PR just for the `residuals()` method first? (so without the robust sandwich stuff)
One question I have from a methods point of view is whether we would like to have an option to "decorrelate" the residuals over the visits (by multiplying with inverse Cholesky factor of cov matrix estimate)

**Comment by danjamstat** [comment]
@danielinteractive I've added code for decorrelated residuals - I think this option would be useful as a diagnostic. One thing I'm not too sure how to deal with at the moment is the use of weights with this option - any thoughts?

**Comment by danielinteractive** [comment]
thanks @danjamstat - cool!

Somehow when looking at https://github.com/openpharma/mmrm/compare/main...danjamstat:mmrm:robust I don't see the decorrelated residuals. As mentioned above, it would be great to make a separate branch for the residuals code and then make a PR towards our main branch, then it will be easier to work together (e.g. I can add comments etc.)

From the methodology side, https://openpharma.github.io/mmrm/main/articles/algorithm.html#linear-model describes how the weights (in G_i) enter the covariance matrix. From that we can see that the Cholesky factor of $\Sigma$ (which we can see being handled with e.g. in https://github.com/openpharma/mmrm/blob/6ff03bacd9543ee302c251961490bc08a022a698/R/tmb.R#L456) needs to be multiplied with $G_i^(-1/2)S_i$ to obtain the Cholesky factor of $\Sigma_i$.

From there we also see that currently for spatial covariance structure we don't have the Cholesky factor at all (because every subject can have a completely different cov matrix). So for now we should restrict the code to non-spatial covariance structures.
