### ISSUE TITLE
Unstructured covariance when time is continuous

### ISSUE THREAD

**Issue by DanChaltiel** [openpharma/mmrm#217]
Hi,

Thank you very much for this great package.

As for now, it seems that you cannot set an unstructured covariance when the time is continuous.

This is not documented, at least not in `?cov_type`, is this a bug or expected behavior?

Note that you can fit such a model using MMRM in `lme4`, following the structure recommended in https://phuse-org.github.io/CSRMLW_bookdown/mixed-models.html#using-the-lme4lmer-function.

Here is a reprex:

``` r
library(tidyverse)

#1) generate a continuous visit time, as a random normal variable of mean VISITN
set.seed(1)
x = mmrm::fev_data %>% 
  mutate(VISIT_NUM = rnorm(n(), mean=VISITN, sd=0.1))
x %>% select(USUBJID, FEV1, ARMCD, VISITN, VISIT_NUM) %>% as_tibble()
#> # A tibble: 800 x 5
#>    USUBJID  FEV1 ARMCD VISITN VISIT_NUM
#>    <fct>   <dbl> <fct>  <int>     <dbl>
#>  1 PT1      NA   TRT        1     0.937
#>  2 PT1      40.0 TRT        2     2.02 
#>  3 PT1      NA   TRT        3     2.92 
#>  4 PT1      20.5 TRT        4     4.16 
#>  5 PT2      NA   PBO        1     1.03 
#>  6 PT2      31.5 PBO        2     1.92 
#>  7 PT2      36.9 PBO        3     3.05 
#>  8 PT2      48.8 PBO        4     4.07 
#>  9 PT3      NA   PBO        1     1.06 
#> 10 PT3      36.0 PBO        2     1.97 
#> # ... with 790 more rows

#2) try to fit with {mmrm} --> error
fit <- mmrm::mmrm(
  formula = FEV1 ~ ARMCD * VISIT_NUM + us(VISIT_NUM | USUBJID),
  data = x
)
#> Error in fit_single_optimizer(formula = formula, data = data, weights = weights, : Assertion on 'coordinates[[1L]]' failed: Must be of type 'factor', not 'double'.

#3) try to fit with {lme4} --> OK
fit2 <- lme4::lmer(
  formula = FEV1 ~ ARMCD * VISIT_NUM + (0 + VISIT_NUM | USUBJID),
  control = lme4::lmerControl(check.nobs.vs.nRE = "ignore"), 
  data = x
)
fit2
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: FEV1 ~ ARMCD * VISIT_NUM + (0 + VISIT_NUM | USUBJID)
#>    Data: x
#> REML criterion at convergence: 3567.715
#> Random effects:
#>  Groups   Name      Std.Dev.
#>  USUBJID  VISIT_NUM 1.394   
#>  Residual           5.889   
#> Number of obs: 537, groups:  USUBJID, 197
#> Fixed Effects:
#>        (Intercept)            ARMCDTRT           VISIT_NUM  ARMCDTRT:VISIT_NUM  
#>            27.4707              3.9041              5.1358              0.1162
```

<sup>Created on 2023-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by danielinteractive** [comment]
Thanks @DanChaltiel for the good question!

So this is expected behavior. Currently, all covariance structures other than spatial ones expect a factor variable for the time points. This is to emphasize that only the order of the time points matters for the model, but not the numeric values. 

Note that your `lme4` call fits a completely different model - there the numeric `VISIT_NUM` variable is used as a random effect in the linear mixed model. 

In principle, it is as easy as 
```r
x$VISIT <- factor(x$VISIT_NUM)
fit <- mmrm::mmrm(
  formula = FEV1 ~ ARMCD * VISIT_NUM + us(VISIT | USUBJID),
  data = x
)
```
but please don't run this here because your R session will crash as you have 800 different time points here, such that the covariance matrix becomes way too large.

I have opened two follow up issues:
- https://github.com/openpharma/mmrm/issues/219 for warning the user of too many time points
- https://github.com/openpharma/mmrm/issues/220 to improve documentation and error message

**Comment by DanChaltiel** [comment]
Thank you very much for your answer.

To summarise explicitly, would you say that it is not possible to have an unstructured covariance matrix in an MMRM when the time is considered continuous?

Of note, [the guide](https://phuse-org.github.io/CSRMLW_bookdown/mixed-models.html#using-the-lme4lmer-function) I used to write the `lme4` call is taken from https://github.com/openpharma/mmrm/issues/93. 
If you are saying that this syntax fits a different model than `mmrm`, I think it is really important to mention it in the upcoming vignette, and maybe tell the authors about it (so they can be explicit too about `VISIT` having to be categorical).

To be honest, I would really appreciate it if you could provide me a `lme4` syntax that could reproduce `mmrm` results, if such a thing exists.

I really look forward to reading the vignette BTW! 😄

**Comment by danielinteractive** [comment]
The point is that if you want to fit an unstructured covariance model, it does not make sense to have a continuous time variable. For continuous time variables (and I mean really continuous, not just the R variable type, but in reality) only spatial covariance structures make sense.

In `lme4`, if you want to try to fit an mmrm with unstructured covariance, you need to make sure that you have a factor variable (same as for `mmrm` package basically).

Does this clarify?

**Comment by DanChaltiel** [comment]
This clarifies a lot, thank you so much, it makes perfect sense.
