### ISSUE TITLE
Allowing interface for covariance outside of formula to support tidymodels interop

### ISSUE THREAD

**Issue by dgkf** [openpharma/mmrm#218]
Prompted by initial MVP in #214, we found that covariance represented through a formula is not particularly well suited to the `tidymodels` ethos. Just to capture some of @yonicd's findings in that process:

### Identified gap

Within `tidymodels`, you can still run an `mmrm` model as a standalone model, where the formula is defined alongside the model specification or model-specific run.

```r
mmrm_spec <- linear_reg() |>
  set_engine("mmrm", method = "Satterthwaite")

mmrm_wflow <- workflow() |>
  add_variables(outcomes = FEV1, predictors = c(RACE, ARMCD, AVISIT, USUBJID)) |> 
  add_model(mmrm_spec, formula = FEV1 ~ RACE + ARMCD * AVISIT + us(AVISIT | USUBJID))
```

However, if you're defining a recipe for data, `mmrm`-style formulas raise errors:

```r
recipe(FEV1 ~ RACE + ARMCD + AVISIT + us(AVISIT | USUBJID), data = fev_data) |>
  step_dummy(ARMCD) |>
  step_interact(terms = c('ARMCD','AVISIT'))
#> Error in `inline_check()`:
#> ! No in-line functions should be used here; use steps to define baking actions.
```

Definitions of model-specific formula terms like the covariance matrix also are not well suited to a recipe definition as they are orthogonal to data cleaning.

### Proposed changes

Although formula-specified covariance might be a convenient shorthand for `mmrm()`, we would need an alternative to support `tidymodels`. I would propose a separate `covariance` argument that accepts a formula (eg `~ us(AVISIT | USUBJID)`) just to keep things relatively transferable. 

Some scenarios and behaviors that I would expect:

```r
# good: covariance structure in formula
mmrm(FEV1 ~ RACE + ARMCD + AVISIT + us(AVISIT | USUBJID), data = fev_data)
```

```r
# good: covariance as an argument
mmrm(FEV1 ~ RACE + ARMCD + AVISIT, data = fev_data, covariance = ~ us(AVISIT | USUBJID))
```

```r
# bad: covariance in formula AND argument
mmrm(
  FEV1 ~ RACE + ARMCD + AVISIT + us(AVISIT | USUBJID), 
  data = fev_data, 
  covariance = ~us(AVISIT | USUBJID)
)
# Error in mmrm():
#   Covariance structure specified in formula and parameter. At 
# most one covariance specification is permitted.
```

Accepting a `covariance` argument here would allow it to be specified as part of the engine

```
mmrm_spec <- linear_reg() |>
  set_engine("mmrm", method = "Satterthwaite", covariance = ~us(AVISIT | USUBJID))
```

### Decisions

- [ ] Add `mmrm(covariance = ...)` param?
    Since a ton of `...` arguments get shuffled into `mmrm_control` and `h_get_optimizers`, this parameter could effectively live in any of them. I think it makes most sense at the top `mmrm` level, but we have other model parameter-relevant things in `mmrm_control` like `drop_visit_levels` and `method`.

**Comment by danielinteractive** [comment]
Great, sounds good @dgkf - I would vote for moving `covariance` into `mmrm_control` since interactive users won't need to know about that - unless they use `recipe` but then we would anyway need a section on that in our introduction vignette which clearly shows that.

**Comment by yonicd** [comment]
I would vote for `mmrm_control` too, but would recommend not having a formula class input, but a function; and convert to formula internally. 

When writing sims it is always a pain to build formulas.

**Comment by danielinteractive** [comment]
@yonicd good point. but not sure how much overhead we then have to maintain the function interface. maybe something very simple could work, like just passing the covariance model type as string, same for the time point and subject ID variable names.

**Comment by yonicd** [comment]
That could work too, but we would still need to validate inputs anyways when reassembling the pieces. I’m not sure it cuts down in overhead.

**Comment by dgkf** [comment]
I think we could accommodate both cases pretty easily. With a default to extract the covariance parameters from `formula`, the behavior would be the same as it currently is:

```r
mmrm <- function(formula, covariance = as.cov_struct(formula), ...) { .. }
```

Having user facing functions for building this object would help expose these behaviors to users in a more programmable way.

```r
cs <- cov_struct(
  "compound symmetry", 
  visit = "AVISIT", 
  group = "ARM", 
  subject = "USUBJID"
)

mmrm(formula, covariance = cs, ...) { .. }
```

And internally we can continue to accept a one-sided formula.

```r
mmrm(formula, covariance = ~cs(AVISIT | USUBJID), ...) { 
  covariance <- as.cov_struct(covariance)
  # ..
}
```

Although this could still happen in `mmrm_control`, I'm partial to keeping these types of operations as close to the user surface as possible so that any errors in coercion between data types is immediately triggered to the user without a complicated backtrace of internal functions.

**Comment by danielinteractive** [comment]
thx @dgkf , that looks good to me. In particular it is important that we can still write the formula as we do it now and then will get automatically picked up by the `covariance` argument via the parsing function `as.cov_struct`.
