### ISSUE TITLE
Clarify in documentation that non-spatial covariance structure needs factor variable

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#220]
Motivation: As shown in https://github.com/openpharma/mmrm/issues/217 it is not obvious right now that time point variable needs to be factor variable for non-spatial covariance structures.

To do:

- [x] Clarify in
	- [x] intro vignette
	- [x] `mmrm()` doc
	- [x] `cov_type` doc
- [x] Improve error message: Currently the user gets `Assertion on 'coordinates[[1L]]' failed: Must be of type 'factor', not 'double'` and they should get something like `Time points variable needs to be a factor`

**Comment by danleibovitz** [comment]
Inserted a check and corresponding error message in R/tmb.R, within the `fit_mmrm()` function; added a corresponding test in test-tmb.R under 'misc'.

Updated the documentation in R/fit.R for `mmrm()`, in cov_struct.R for `cov_types`, and in the intro vignette.
