### ISSUE TITLE
Fix publication references

### ISSUE THREAD

**Issue by chstock** [openpharma/mmrm#222]
Not directly a bug:  In the description file a reference is made to "Mallinckrodt, Lane and Schnell (2008)", suggesting this publication has 3 authors. However, the actual publication behind the DOI link has these 3 plus 2 more authors. Consider e.g. Mallinckrodt, Lane, Schnell, et al./ and colleagues/ and others.

**Comment by danielinteractive** [comment]
thanks @chstock !

**Comment by chstock** [comment]
Another question related to scientific references (in vignettes): We do not specifiy a certain citation style in the header of the vignettes. There seems to be a default that is applied. What happens with this default is that first names of authors in the reference list are either fully shown or abbreviated, depending on the entry in the bib file. I think it would be nicer if they are all abbreviated (as this is what you commonly see in journals). We could look for another citation style and apply that. The alternative, in order to be consistent, is to be consistent in the bib file. There are currently not too many refs in the vignettes but there may be a few more in the future. This could be fixed in one go. Happy to be assigned to this.

**Comment by danielinteractive** [comment]
Sounds good thanks @chstock , feel free to assign this to yourself and start

**Comment by danielinteractive** [comment]
Hi @chstock any help needed with this?

**Comment by chstock** [comment]
Hi @danielinteractive, thanks -  generally all fine from my side. I should be able to do this next week. If you have or anyone has a preferred style file (for author-year refs), happy to use that one. I was looking for something publisher/ journal independent that is free to use and haven't quite made up up my mind...

**Comment by danielinteractive** [comment]
Thanks @chstock I don't mind, any "standard" style is fine

**Comment by danielinteractive** [comment]
Hi @chstock do you think you can finish this week?

**Comment by chstock** [comment]
Hi @danielinteractive, apologies for the delay. I will try this week and hope to have the PR Monday morning at the latest.
