### ISSUE TITLE
Consider adding support for multiple imputation (incl. pooling results for inference via emmeans)

### ISSUE THREAD

**Issue by Generalized** [openpharma/mmrm#227]
There is a need for the multiple imputation, either as the default or supportive **sensitivity** (often requested nowadays!) analysis, even considering the potential unbiasedness of MMRM in case pattern-ignorable missingness.

Most of the time, in R it's handled via multi-level models - mixed models, like lme4. There is also some work regarding nlme ( https://cran.r-project.org/web/packages/mitml/mitml.pdf | https://github.com/simongrund1/mitml/issues/16 )

In SAS we have the PROC MIANALYZE procedure. It would be nice to have the pooling rules combined with MMRM output (or contribute to the existing packages) after using certain some MI procedure (e.g. mice?) to be able to make inference (analysis of certain contrasts via emmeans) after performing multiple imputation.

emmeans seems to give some support already: https://github.com/rvlenth/emmeans/issues/80

EDIT: for the mice package, also broom::tidy() or glance() have to be defined for each class (either gls or mmrm), as mice v>3 uses "tidiers" to access necessary parts of models (estimates, var-cov, degrees of freedom) in an unified way.

EDIT: After some research it seems I found an already existing package cooperating with mmrm:
https://cran.r-project.org/web/packages/rbmi/index.html
https://github.com/insightsengineering/rbmi/issues/384

**Comment by danielinteractive** [comment]
Hi @Generalized , yes, rbmi is the package I would recommend for this purpose

**Comment by Generalized** [comment]
Thank you @danielinteractive 
Did you, maybe, experiment with mmrm and rbmi (or any other package suitable for mmrm) or somehow collaborate on making it? I mean - is this a part of your "joint initiative" or a completely separate project?
I have a few questions to confirm/answer in order to decide whether I can use it yet it seems the Authors are busy right now. I'm going to investigate the code and modify it according to my needs soon (it seems it won't handle cLDA out of the box due to the specification of model), but maybe -in the meantime- you or someone in your Team have some thoughts to share about these topics I asked here:  https://github.com/insightsengineering/rbmi/issues/384 ?
