### ISSUE TITLE
Satterthwaite degree of freedom for Sandwich Estimator

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#230]
in`clubSandwich`, there is one implementation for `gls`, see https://github.com/jepusto/clubSandwich/blob/main/R/coef_test.R.
https://github.com/jepusto/clubSandwich/blob/main/R/get_arrays.R
in _Variance estimation for complex surveys using replication techniques_ Rust and Rao suggest using 
![image](https://user-images.githubusercontent.com/36079400/215654444-15b11a6a-f548-4159-84dd-b8ec3ec82ea7.png)

However, when using similar method for the Satterthwaite d.f. for asymptotic covariance, got very strange result for these sandwich estimatros. The equation is not used, but used another formula

![image](https://user-images.githubusercontent.com/36079400/217688222-0461eb35-0b93-4b28-98fb-c8e5464c2137.png)

- [x] Find out how important is this in applications
- [x] Further check `clubSandwich`
    - [ ] understand the algorithm used in `clubSandwich`
    - [ ] implement the `Satterthwaite` d.f. for the two new added sandwich covariance
    - [ ] or, directly call `clubSandwich` in `mmrm` package (so that the `summary(mmrm_fit)` works)
    - [x] or, implement as the paper describes
- [x] ~~create a vignette that combines all the d.f. things, including residual, Satterthwaite, Kenward-Roger, (between-within), etc; currently they are in different vignettes and not very convenient to understand these things~~ add vignettes in Satterthwaite degree of freedom
- [x] add news

**Comment by danielinteractive** [comment]
@chstock Hi Christian, any opinion from your side how important this would be, i.e. having a Satterthwaite degrees of freedom in combination with robust sandwich estimator for the coefficients covariance matrix? Note that SAS does not offer this
