### ISSUE TITLE
Add `tidymodels` to documentation

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#231]
To do:

- [ ] README 
	- [ ] consider restructuring the "Main Features" list a little bit to nicely fit that in
- [ ] intro vignette
	- [ ] consider adding new section about interfaces or so - can then also put `emmeans` in there

**Comment by yonicd** [comment]
Have some time this weekend, will set goal to get it up for review. Apologies for delay.

**Comment by danielinteractive** [comment]
Sounds good, thanks @yonicd !

**Comment by yonicd** [comment]
I restructured the readme section, but I noticed that the current intro vignette rmd was not deployed to pages. Wanted to verify you see same thing.

**Comment by danielinteractive** [comment]
Thanks @yonicd for working on it, on pages you can select the `main` version, then you see the current main branch state of vignettes:
<img width="877" alt="image" src="https://github.com/openpharma/mmrm/assets/1071227/c6e3fa7a-38ce-4825-8649-d675f808f2d9">
By default we show the CRAN release version (so currently 0.2.2) so that users are not confused by unreleased things.

**Comment by yonicd** [comment]
Thanks for the clarification. Will continue on refactor.

**Comment by danielinteractive** [comment]
Thanks @yonicd , how about starting with a draft PR maybe so we can align on the direction?
