### ISSUE TITLE
[Feature request] Adding the CR2 empirical/robust covariance estimator for small-sample cases (like in clubSandwich)

### ISSUE THREAD

**Issue by Generalized** [openpharma/mmrm#241]
Dear Authors,

I noticed that recently you enhanced the awesome mmrm package by adding several ways to calculate the covariance estimator. I noticed the classic [Liang-Zeger] sandwich (CR0) and the jacknife (CR3). Perfect choice - reproducing what's available in SAS.

However, several (12 since 2018) times I was asked by the sponsors and one time from a local regulator to account for the small sample*. 8 times (5 times by the same sponsor) I was asked to use the "bias-reduced" Pustejovsky's CR2-type estimator. They refused to accept the CR0 also this time and I can do nothing with this decision. This is interesting, as the CR2 is not available in SAS yet, as far as I know. But evidently the cooperating biostatisticians recognized the the Pustejovsky's work and clubSandwich package and now they ask me for it.

(* by the way, also GEE has own small-sample adjustments, e.g. Morel's and other implemented in the geesmv package)

The CRxx terminology for clustered case is similar to the classic heteroscedasticity-consistent HCxx we know from the sandwich package. 
![obraz](https://user-images.githubusercontent.com/60151643/220605979-486378f8-67f1-42ad-a6b4-ac5b52461f2a.png)

Currently the team nlme::gls() + emmeans (giving approximate Satterthwaite) + clubSandwich (CR2) can do the job for me, as it served this way for a longer time, but unquestionably I would prefer to switch to **mmrm** finally, as it's polished and well-featured *awesome* solution I've been waiting for years!

Would it be possible to add also the CR2? Maybe you could take the code directly from the clubSandwich package or find the necessary formulas (and R examples) in the links I provided below. Especially the 2 first may be helpful.

References: 
- [Small-Sample Methods for Cluster-Robust Variance Estimation and Hypothesis Testing in Fixed Effects Models](https://arxiv.org/pdf/1601.01981.pdf)
- https://www.jepusto.com/handmade-clubsandwich/
- http://jepusto.github.io/clubSandwich/articles/panel-data-CRVE.html
- https://cran.r-project.org/web/packages/clubSandwich/clubSandwich.pdf

**Comment by danielinteractive** [comment]
Thanks @Generalized for reaching out on this. We'll have a look at this, maybe @clarkliming if you have time you could have a first assessment how difficult it would be to add CR2?

**Comment by clarkliming** [comment]
CR2 is similar to CR0 and CR3, and this is not too different. From my rough estimate this won't be difficult

**Comment by danielinteractive** [comment]
Great thanks @clarkliming , then I would say good to start on this one :-)
