### ISSUE TITLE
Alternative link functions?

### ISSUE THREAD

**Issue by wlandau** [openpharma/mmrm#251]
MMRM-like generalized linear mixed models come up a lot in pharma, particularly for binary data, and I think it would help address these cases to have the ability to set non-identity links like logit and probit. Apologies if this is already possible and I missed something in the documentation.

**Comment by chstock** [comment]
This actually sounds like an interesting idea to me. I agree, it may be relevant particularly for binary endpoints. Not sure why there does not seem to have been much attention on generalized MMRMs (my impression), both from the methods side and also, I think, from the applied side. PROC GLIMMIX could fit such models.

**Comment by danielinteractive** [comment]
Thanks @wlandau - actually for this package in particular we are focusing only on specific Gaussian models. For other outcome distributions please check out `glmmTMB` which I think already allows fitting those models. (Note that the main motivation for `mmrm` was to have adjusted degrees of freedom, higher speed, etc. for specific Gaussian models)
