### ISSUE TITLE
Add tests for 'fitted()' method

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#253]
Motivation: 
https://github.com/openpharma/mmrm/blob/c9dd43bd66b552d8b1abde41e53d17fc1f0749ef/tests/testthat/test-tmb-methods.R#L31-L35
is not too convincing as we are currently just testing for the correct length here. It would probably be good to test 'fitted' against some  examples from SAS and or nlme.

**Comment by danielinteractive** [comment]
Thanks @kkmann , yeah agree this is not specific enough. I guess we assessed this as low risk given simple code in https://github.com/openpharma/mmrm/blob/main/R/tmb-methods.R#L38 and we have lots of integration tests that look at the `beta` coefficients vs. SAS. But yeah we can definitely increase tests here more specifically.

**Comment by clarkliming** [comment]
> How does fitted handle situations where input data is reordered or observations are dropped to create full rank matrices?

in `object$tmb_data$x_matrix` it is already reordered and the observations are dropped (to remove NA) and column dropped (to create full rank matrix). If some rows are still needed, we can use `predict` method here.

Personally I do think the need for extra tests is not needed for this simple case of $X \beta$. with the fact that we always reorder the input data, we can't do much if other implementations does not reorder the imput data ( the result should be the same)

**Comment by danielinteractive** [comment]
Let's add some additional tests. I do agree risk is low, but it does not cost us much and increases confidence in the package further.
