### ISSUE TITLE
Fix documentation error in spatial exponential covariance function

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#258]
I think https://openpharma.github.io/mmrm/latest-tag/articles/covariance.html#spatial-exponential is not correct - it should be rho to the power of d, not -d, right?

The implementation is correct https://github.com/openpharma/mmrm/blob/c9dd43bd66b552d8b1abde41e53d17fc1f0749ef/src/covariance.h#L134

**Comment by danielinteractive** [comment]
Could be, @clarkliming what do you think?

**Comment by clarkliming** [comment]
yes you are right. Thank you for spotting this.

**Comment by clarkliming** [comment]
already resolved in #213, see https://github.com/openpharma/mmrm/pull/213/files#r1060579515
