### ISSUE TITLE
Add `get_cov_chols(<tbd>, type, theta)` R function to expose C++ cov Cholesky factor

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#263]
- for all individuals with multiple time points (incl. unobserved ones in data set before) at once
- return list of Cholesky factors
	- needs to be appropriately weighted already

First idea was this:
- idea see https://github.com/openpharma/mmrm/blob/main/src/mmrm.cpp#L65 and following until line 93 - this could be factored out in helper function (then also need tests again for that)
- additional inputs needed:
	- `n_groups`
	- `n_visits`
	- `n_subjects`
	- `subject_zero_inds`
	- `visits_zero_inds`
	- `subject_n_visits`
	- `coordinates`
	- `weights`
	- this could be put in `tmb_data` and maybe just keep x and y empty or something

Second idea is:
- just do it on the R side, see https://github.com/openpharma/mmrm/blob/main/R/tmb.R#L471 as start
- use the reported Cholesky factors
- of course don't do any optimization

**Comment by clarkliming** [comment]
question: in `TMB`, report the `covariance matrix` for each subject too? will this be sufficient?

**Comment by danielinteractive** [comment]
Hi @clarkliming , no that is unfortunately not sufficient, because we will need to 
1) also have the covariance matrix for new patients and/or new time points
and
2) for new `theta` values (which would be ok with reporting, but that is not sufficient)

**Comment by clarkliming** [comment]
for new subjects, I do think we have to jump out of the reporting and implement another interface in R

**Comment by danielinteractive** [comment]
Yep exactly, more like Rcpp interface
