### ISSUE TITLE
instead of `select_matrix` and matrix calculation, use subset rows

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#270]
currently to obtain a subset of covariance matrix, we use `select_matrix` to obtain the subset. This involves the following calculation
1. contruct select matrix (n_subject_visits * n_visits) with filled 0
2. fill 1 for specific positions in the select matrix
3. do the matrix calculations (select_matrix %*% covariance %*% t(select_matrix)) 

instead, consider using matrix subsetting
1. construct return matrix (n_visits * n_visits), no need to initialize values
2. for the given rows, take the corresponding rows and colums

With this, we are able to harmonize the input of coordinates (they are all kind of matrix now, matrix<double> as input; then obtain the std::vector<int> subject_visits and this can be used directly in `chol_cache.R`) but this is can be resolved in another issue

related to #110

**Comment by danielinteractive** [comment]
OK thanks Liming! Let's move it to the backlog for now.

**Comment by danielinteractive** [comment]
Related to Eigen version 3.4 which is not available in CRAN yet:
