### ISSUE TITLE
predict() returns error message if no outcome data at certain visit for certain group

### ISSUE THREAD

**Issue by nociale** [openpharma/mmrm#281]
To do:
- [x] Add reprex as new integration test
- [x] Fix bug:
	- [x] return understandable warning message
- [x] Ensure all tests pass
- [x] Note: no NEWS update needed as we don't have a release with predict yet.

Report: I am trying to use the `predict()` function from a `mmrm` fit object. In my case, I have no outcome data at certain visits for at least one treatment group. I have no problem in fitting the model and extracting marginal means using `emmeans`, but I am having an issue with predict(). Please find below an example:

```r

# Add fake visit only for one treatment group
new_fev_data <- rbind(
  fev_data,
  fev_data %>% 
    filter(ARMCD == fev_data$ARMCD[1], AVISIT == "VIS1") %>% 
    mutate(AVISIT = "VIS5", FEV1 = rnorm(n(), mean = 45, sd = 5))
)

# Fit mmrm
fit <- mmrm(
  formula = FEV1 ~ ARMCD * AVISIT + us(AVISIT | USUBJID),
  data = new_fev_data
)

# Predict
predict(fit, fit$data)
```

Error message:

```r
Error in h_get_prediction(tmb_data, object$theta_est, object$beta_est,  : 
  Assertion on 'beta' failed: Must have length 10, but has length 9.
```

**R session info**

R version 4.2.1
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

**Comment by danielinteractive** [comment]
Great, thanks @nociale for posting! @clarkliming can you please have a look?

**Comment by clarkliming** [comment]
the reason of this issue is that, in the new data matrix is singular, and VIS5 * ARM is dropped during the fit, leading to $\beta$ is truncated to the rank of the data matrix. With that information, I kind want to say that the prediction with the old fit does not make sense (it only makes sense during the fit, but if the new data contains non-singular VIS5 * ARM then the new prediction is not "correct")

but we can still provide the prediction based on the truncated matrix. Is that OK?

**Comment by nociale** [comment]
Thanks for looking into it. 

- Shouldn't marginal means computations also be affected by the same issue? 
- May a warning message be more appropriate than an error message?

**Comment by danielinteractive** [comment]
Ah wait I misunderstood. Basically the point here is that already the original model fit had a truncation. Yes, in that case we should use the truncated matrix (and maybe add a warning). So that seems to be an edge case we missed during initial tests.
