### ISSUE TITLE
Make a note about `Kenward-Roger-Linear` in `mmrm_control`

### ISSUE THREAD

**Issue by henrikibster** [openpharma/mmrm#285]
When using the Kenward Rogers method it would be nice if it was mentioned in the help-file form mmrm_control, that "Kenward-Roger-Linear" is the one to use (and not "Kenward-Roger"), if you wish to recreate results from SAS where the Kenward-Roger option has been used. It is mentioned in the vignette, but it would be nice to have in the help file also

**Comment by clarkliming** [comment]
in SAS there are several ddfm choices, there are `kr` and `kr(linear)` options, see [sas_wrapper("kr(linear)", "cs", "kr1_cs")](https://github.com/openpharma/mmrm/blob/1ce4e4e377f9217403434830fe428bc8b0da592f/design/KR/kr.R#L28)

so here if you want to match SAS, Kenward-Roger-Linear should be matching kr(linear) and Kenward-Roger should be matching kr. However, there could be differences in parameterization so we do expect differences (not exact match).

Could you please more information on which covariance structure you are using? and have you tried with using "kr(linear)" in SAS to compare the results?

**Comment by henrikibster** [comment]
Thank you very much for the speedy reply!
In the example we were looking at (unstructured covar), we got the same results when using linear Kenward-Roger in MMRM, and 'ordinary' Kenward-Roger in SAS. 
In the vignette https://cran.r-project.org/web/packages/mmrm/vignettes/kenward.html it appears that this interpretation is correct: " _However, the differences can be small and will not affect the inference. If you would like to match SAS results for the unstructured covariance model, you can use the linear Kenward-Roger approximation._"

**Comment by clarkliming** [comment]
> Thank you very much for the speedy reply! In the example we were looking at (unstructured covar), we got the same results when using linear Kenward-Roger in MMRM, and 'ordinary' Kenward-Roger in SAS. In the vignette https://cran.r-project.org/web/packages/mmrm/vignettes/kenward.html it appears that this interpretation is correct: " _However, the differences can be small and will not affect the inference. If you would like to match SAS results for the unstructured covariance model, you can use the linear Kenward-Roger approximation._"

thank you for the clarification. Unstructured covariance in SAS seems to be using the $\Sigma$ as their parameterization method, while we are using the cholesky, this leads to the difference. (SAS seems to have identical results for KR and KR(linear) for unstructured)

for other covariance matrix, it is generally Kenward-Roger-Linear matches kr(linear), Kenward-Roger matches kr. So I think we can add some more information specially for the KR with Unstructured covariance
