### ISSUE TITLE
`make_unique` is a function in std since C++14

### ISSUE THREAD

**Issue by fenguoerbian** [openpharma/mmrm#295]
When I install the package from source I get the error:

`error::make_unique is not a member of ‘std’`

I think this is due to the fact that `make_unique` is a member in `std` since C++14.

`make_unique` is used here https://github.com/openpharma/mmrm/blob/755d42638e2d901b2b6038817416a95d5fd3159a/src/chol_cache.h#L109

So I'm suggesting to add some requirement in the package to indicating a use of C++ complier at least C++14.

Maby in DESCRIPTION

```
SystemRequirements: C++14
```

Or specify the C++ standard in src/Makevars (and even src/Makevars.win)

```
CXX_STD = CXX14
```

**Comment by clarkliming** [comment]
thank you we will do this

**Comment by clarkliming** [comment]
@fenguoerbian could you please try branch `272_reduce_replicated` we just added the system requirements there

**Comment by fenguoerbian** [comment]
@clarkliming That installs just fine, thanks a lot.
