### ISSUE TITLE
Contribute `mmrm` examples to `CAMIS` repository

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#303]
Now that we have our own comparison vignette etc, it would be good timing to make sure `mmrm` is seen in the PSI AIMS `CAMIS` (Comparing Analysis Method Implementations in Software) repository. We could also add examples for `glmmTMB` for completeness. We can also add topics of our interest, e.g. degrees of freedom calculation, speed, etc.

References:
- https://psiaims.github.io/CAMIS/R/mmrm.html
- https://psiaims.github.io/CAMIS/Comp/r-sas_mmrm.html

Sources to propose changes in the PR:
- [ ] https://github.com/PSIAIMS/CAMIS/blob/main/R/mmrm.qmd
- [ ] https://github.com/PSIAIMS/CAMIS/blob/main/Comp/r-sas_mmrm.qmd
	- [ ] maybe ask for the source code first, cannot find it on the repo right now

**Comment by andreaczhang** [comment]
Hi Daniel @danielinteractive , I am a member of CAMIS, and we have discussed adding documentation of `mmrm` package in this week's update meeting. It's great to see that this has already been discussed here!

I'm wondering if there is anyone in the MMRM team who has volunteered to take the task? 

If there is someone who wants to do it, I'd be glad to be the contact person on behalf of CAMIS to figure out practical workflows etc. 

If not, I can volunteer to do this as well. Would be a good learning opportunity to use the great package!

Just let me know what you think. Thank you very much!
Chi

**Comment by danielinteractive** [comment]
Thanks @andreaczhang for reaching out - yeah I think @yonicd might be volunteering from our side? :-)

**Comment by yonicd** [comment]
Happy to facilitate. Let me know when is a good time to connect and I will start.

**Comment by andreaczhang** [comment]
> Happy to facilitate. Let me know when is a good time to connect and I will start.

@yonicd Thank you! Right now we're working on some documentation for contribution. I'll let you know once it's ready!

**Comment by DrLynTaylor** [comment]
Thanks @andreaczhang for kicking this off.  @yonicd, would you like me to talk you through the location of the files in our repo that we'd like updating.  The quarto files build directly into the website so we have a few standards that we'd like followed.  Would this Friday 27th be convenient if I set up a call?

**Comment by yonicd** [comment]
That would be great. Thank you

**Comment by DrLynTaylor** [comment]
Can you send me your email address on here or to Lyn.taylor@parexel.com and i'll set up a call. Thanks.

**Comment by yonicd** [comment]
Hi

I seems your email spam filter is set to ninja warrior and I couldn't send my info through email :)

my contact info is yoni@pinpointstrategies.io

thanks

**Comment by DrLynTaylor** [comment]
Ha ha !!  Yes the joys of working in pharma, everything is locked down.  I will send you an email, let me know if you haven't receive it by end of day. Thanks.

**Comment by yonicd** [comment]
@danielinteractive can you fork the camis repo into the openpharma org please. Once it is there I will start to migrate content to the fork and create a PR to the upstream (per contribution guidance from @DrLynTaylor)

**Comment by yonicd** [comment]
@danielinteractive it was also agreed that {brms.mmrm} will also be listed in the CAMIS directory

**Comment by yonicd** [comment]
@danielinteractive that page doesnt seem to have been effected by the content i created for PR https://github.com/PSIAIMS/CAMIS/pull/119

**Comment by danielinteractive** [comment]
@yonicd I think it is separate page that needs to be modified (in separate PR)

**Comment by yonicd** [comment]
[pages](https://psiaims.github.io/CAMIS/Comp/r-sas_mmrm.html) were merged. i think this issue can be closed
