### ISSUE TITLE
return (conditional) covariance matrix in `predict` function

### ISSUE THREAD

**Issue by clarkliming** [openpharma/mmrm#306]
currently only the diagonal elements are returned, and to support simulate method, the full matrix is needed.

**Comment by clarkliming** [comment]
while implementing this, a question comes to my mind: is the simulate method, giving simulations on $\theta$, or ($\theta$ and $\beta$)?

I think we should give the latter one, what do you think @danielinteractive ?

**Comment by clarkliming** [comment]
idea: conduct the simulation based on the covariance in C++ directly, instead of returning the list of covariance matrix for each subject.

**Comment by danielinteractive** [comment]
Hm - it could be beneficial to do the simulation in R to preserve readability for R developers?

**Comment by danielinteractive** [comment]
> while implementing this, a question comes to my mind: is the simulate method, giving simulations on θ, or (θ and β)?
> 
> I think we should give the latter one, what do you think @danielinteractive ?

good question - let's work on this in https://github.com/openpharma/mmrm/issues/308
