### ISSUE TITLE
Amend prediction vignette with approach / algorithm for `simulate()` method

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#308]
Before finishing https://github.com/openpharma/mmrm/pull/296, let's first align on the approach and algorithm for the simulation from the predictive distribution functionality.

- In particular, one detail will be on what we condition / what uncertainty to take into account.
- Also what the alignment between `predict()` (`interval = c("confidence", "prediction")`) and `simulate()` (maybe `method = c("conditional", "marginal")`) arguments need to be
- And how much we can follow "standard" of `simulate()` from other packages

@danleibovitz @clarkliming one of you could work on this one first?
@kkmann @chstock we will count also on your opinions re: the conditioning question :-)

**Comment by clarkliming** [comment]
some initial idea:

1. with `simulate(mmrm_fit, new_data)` we create simulated $y$ conditional on $\theta$ and $\beta$
2. if other $\beta$ and $\theta$ is needed, use something like `simulate(mmrm_fit, new_data, beta_new, theta_new)`; still this is conditional on $\beta$ and $\theta$
3. if the variance of $\beta$ is to be taken into consideration, sample $\beta$ first and then simulate
