### ISSUE TITLE
Add `print` method for `mmrm_tmb`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#31]
This is nice for handling the results and will make testing of the package easier.

To do:

- [x] see how other packages are doing it, e.g.:
	- [x] `glmmTMB`: glmmTMB uses `print.glmmTMB` to present their objects, with the typical model output that one would expect. Very similar to what is spec'd below. 
	- [x] `lme4`: for lmList4 they use `show` to print out a model summary (coded within the function body), for merMod they first spec a S3 `print` method, and then call that in the S4 `show` method body. The difference seems to be that lmList4 inherits the print method from `lme` objects from the `nmle` package. 
- [x] do a nice first version (does not need to be perfect)
	- [x] in https://github.com/openpharma/mmrm/blob/main/R/tmb-methods.R
  - [x] include formula, data, covariance structure (can reuse functions from printing the mmrm object)
  - [x] plus include REML vs ML used, optimizer used, convergence yes/no
  - [x] iterations counts
  - [x] see other tmb methods for how to document it
	- [x] add test in corresponding test file https://github.com/openpharma/mmrm/blob/main/tests/testthat/test-tmb-methods.R

**Comment by BrianLang** [comment]
I'd take this issue. Can you assign it to me?

**Comment by danielinteractive** [comment]
Awesome, thanks @BrianLang ! I just added you as a collaborator. Please let me know if any questions. I will also add you to our standup meetings and Slack channel for communication.

**Comment by BrianLang** [comment]
Great, thanks a lot, also for the added info in the issue description!

**Comment by BrianLang** [comment]
- [ ] see how other packages are doing it, e.g.:
	- [ ] `glmmTMB`: will look at this soon.
	- [x] `lme4`: for lmList4 they use `show` to print out a model summary (coded within the function body), for merMod they first spec a S3 `print` method, and then call that in the S4 `show` method body. The difference seems to be that lmList4 inherits the print method from `lme` objects from the `nmle` package. 

I see that we already have a `print.summary` method for `mmrm` objects, do we want a print method as well as a show? Kind of unclear as to when I'd want each of them. I don't think I've used `show()` before.

**Comment by danielinteractive** [comment]
Maybe it should be a print instead of a show method for the S3 object here actually. I think it would be nice so that when the user just looks at the fitted object without saying summary then they get a meaningful representation instead of a very long list being printed on the console.

**Comment by danielinteractive** [comment]
Thinking about it more let's do it also here on the lower level mmrm_tmb object, and then this is inherited by the mmrm object. I added a few more detail ideas to the description.

**Comment by BrianLang** [comment]
Okay, let's make an S3 `print.mmrm_tmb` and I'll use the approaches in the h_print_* methods. 
Are those methods, which are used in print.summary.mmrm, presenting the output in the way you'd like for the base print method? 

- [x] see how other packages are doing it, e.g.:
	- [x] `glmmTMB`: glmmTMB uses `print.glmmTMB` to present their objects, with the typical model output that one would expect. Very similar to what you've spec'd in the issue description.

**Comment by danielinteractive** [comment]
Cool, yeah that format should be fine, but feel free to propose modifications, thanks Brian for working on this!
