### ISSUE TITLE
File name with '<>' causes impasse with Windows git

### ISSUE THREAD

**Issue by danleibovitz** [openpharma/mmrm#320]
**Summary**

The `<` and `>` in `design/predict_interval/un_kenwardroger<linear>.csv` create an impasse for windows upon fetching of new commits.

**OS / Environment**

- OS: Windows 11 (Version: 10.0.22621; Build: 22621; 64-bit operating system, x64-based processor)

**Comment by danielinteractive** [comment]
Oh wow, but why do we have that file name in the first place? Need to check that

**Comment by danleibovitz** [comment]
> Oh wow, but why do we have that file name in the first place? Need to check that

@clarkliming added that file recently, maybe just written in manually. All good though, simple update :)

**Comment by DanChaltiel** [comment]
This also makes it challenging to install the dev version from GitHub.
For instance, `renv::install("openpharma/mmrm")` failed because of this file (tested on Win 10).
