### ISSUE TITLE
Add additional methods

### ISSUE THREAD

**Issue by ddsjoberg** [openpharma/mmrm#324]
This modeling pkg is awesome! I wish I had known about it when I was doing applied work. It looks like it's so much easier to specify common spatial correlation structures!

I was poking around and noticed the package is missing a few methods found in most regression modeling packages.
- `terms()`
- `model.matrix()`
- To be noted, `weights(model)` return a vector of the same length of the original data frame passed to the model, but not of the length of `model.frame(model)` (where NA values have been removed). With `lm()` or `glm()`, the vector obtained with `weights()` is of the same length as `model.frame(mod)`
- A `tidy()` method would also be amazing. The generic function is exported from the {generics} pkg, whose only purpose to to export a few generics (as in, the lightest-weight dependency one could imagine).

**Comment by ddsjoberg** [comment]
Hey hey @danielinteractive !

I started work on the `model.frame()`, `terms()`, and `weights()` updates. But before I can make further progress on them, I have a question about the mmrm `model.frame()` S3 method.

Generally, we expect `model.frame()` to return a data frame with the number of rows used in the analysis. The mmrm method has arguments to include/exclude various variables from the returned data frame. The data frame returned excludes missing obs only from the variables included in the output. 

In this example, there are missing observations in the outcome but not in the covariates. The implication is that if the data framed returned with the default args has 800 rows (the outcome variable is not returned), and the data frame returned when the outcome is added is only 537 (the number of obs used in the modeling).

``` r
library(mmrm)

formula <- FEV1 ~ RACE + SEX + ARMCD * AVISIT + us(AVISIT | USUBJID)
object <- fit_mmrm(formula, fev_data, weights = rep(1, nrow(fev_data)))

# mmrm model.frame() returns differnet number of obs depending on fn args
# generally, we expect model.frame() to return a df with the number of rows/obs utilized in the model
model.frame(object) |> nrow()
#> [1] 800
model.frame(object, include = c("response_var", "subject_var")) |> nrow()
#> [1] 537

# example with the standard lm() fn
lm(FEV1 ~ RACE + SEX + ARMCD * AVISIT, fev_data) |> 
  model.frame() |> 
  nrow()
#> [1] 537
```

<sup>Created on 2023-08-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you think we should update the mmrm `model.frame()` method to return the same number of obs for each call (the observations utilized in the model), regardless of what variables are selected in the fn arguments?

**Comment by danielinteractive** [comment]
Thanks @ddsjoberg , good observation! Yeah I think we might want to always only have the observations used in the modeling returned, independent of whether to include the outcome or not. Please have a look at current documentation and unit tests and see what would break / need to be adapted.
