### ISSUE TITLE
Replicate SAS Proc Mixed in MMRM

### ISSUE THREAD

**Issue by PD710** [openpharma/mmrm#327]
Hi all,

I am trying to replicate SAS proc mixed in MMRM using R. 

For example: the SAS code looks like this

PROC MIXED data=my_data;
CLASS subjectID treatment visitnum;
MODEL y=treatment visitnum treatment*visitnum /solution ddfm=kenwardroger;
repeated visitnum/type=un sub=subjectID;
run;

In MMRM the code I attempted looks like this: 

mmrm(formula=Y~treatment*visitnum+us(visitnum|subjectID), data=my_data, weights=rep(1, nrow(Y)),
control=mmrm_control(method="Kenward-Roger"))

However, the outputs are slightly different starting at the second or third decimals for the covariate & intercept estimates. I noticed a similar situation when comparing p-values (for example: SAS proc mixed would give 0.0059 where as MMRM in R would give 0.00554)

While both outputs provide the same conclusion, I am wondering if it's possible to replicate the exact same results in R using MMRM. Any feedback or sharing experiences of replicating a similar SAS proc mixed model in mmrm or pointers in my code would be appreciated !

**Comment by danielinteractive** [comment]
Hi @PD710 ,

thanks for asking, as mentioned in https://openpharma.github.io/mmrm/latest-tag/articles/kenward.html#parameterization-methods-and-kenward-roger (last sentence) you can try to use the Kenward-Roger-Linear method, cf. https://openpharma.github.io/mmrm/latest-tag/reference/mmrm_control.html

Does that help?

Cheers
Daniel

**Comment by danielinteractive** [comment]
Closing because stale
