### ISSUE TITLE
Clean up the "Articles" dropdown menu

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#336]
Currently we have on `main` version https://openpharma.github.io/mmrm/main/:
<img width="505" alt="image" src="https://github.com/openpharma/mmrm/assets/1071227/a0d531f0-30db-40d6-b017-468d7369be8f">

To do:
- [x] Get rid of the `subsections` folder entries producing `UNKNOWN TITLE`
- [x] Introduce a useful order for the remaining vignette entries

It will be good to do this before the 0.3 release so that users coming to our page are not confused by this (as by default the landing page is the current release)

**Comment by clarkliming** [comment]
we can follow https://dplyr.tidyverse.org/
