### ISSUE TITLE
Double check the combination of Satterthwaite and empirical cov estimators

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#339]
I am bit confused at the moment how these work together. 

- In SAS it is not possible at all to combine these it seems because SAS will force ddfm to Between-Within when using Empirical cov estimator
- Currently in mmrm package we don't use the Jacobian at all for Satterthwaite in this case, but we also don't proactively forbid the combination or are transparent about it

To do:

- [ ] Understand if theoretically these can be combined or not
- [ ] If not, then don't allow it
- [ ] If yes, then make sure we do the correct calculations
	- [ ] double check we have numerical integration tests comparing with another software if possible

**Comment by clarkliming** [comment]
> * In SAS it is not possible at all to combine these it seems because SAS will force ddfm to Between-Within when using Empirical cov estimator
SAS only provides "Empirical" option, and do not provide BRL or Jackknife. And you are right SAS do not allow Satterthwaite d.f. for emprical standard errors
> * Currently in mmrm package we don't use the Jacobian at all for Satterthwaite in this case, but we also don't proactively forbid the combination or are transparent about it

Actually Jacobian is used, in `emprical.cpp` it uses `derivarives.h` (and autodiff is included here)

> To do:
> 
> * [ ]  Understand if theoretically these can be combined or not

According to Bell, Robert M., and Daniel F. McCaffrey. "Bias reduction in standard errors for linear regression with multi-stage samples." Survey Methodology 28.2 (2002): 169-182. it is allowed to combine Satterthwaite and Empirical methods

![image](https://github.com/openpharma/mmrm/assets/36079400/98d1bc09-8387-457e-bff0-0b3cd80e4c46)
and this paper also displays its results of empirical covariance and Satterthwaite d.f. 
![image](https://github.com/openpharma/mmrm/assets/36079400/6c24454c-fcd2-4f9e-a20f-c68cb0fe21c9)


> * [ ]  If not, then don't allow it
> * [ ]  If yes, then make sure we do the correct calculations

I think I am doing it right but maybe someone could double check the code I have?

>   * [ ]  double check we have numerical integration tests comparing with another software if possible

already compared with gls implementations, see https://github.com/openpharma/mmrm/blob/5b2c17174474c37218dd36797d2d4c8de6b0a9ac/tests/testthat/test-empirical.R#L288

**Comment by danielinteractive** [comment]
Thanks @clarkliming , that sounds great!

I think this can be closed then since you also put the details in the Satterthwaite vignette already, and we will improve documentation in general in #337 

 Thanks!
