### ISSUE TITLE
Predict template for tidymodels

### ISSUE THREAD

**Issue by yonicd** [openpharma/mmrm#342]
This issue came up from working on PR https://github.com/openpharma/mmrm/pull/325

There is a blind spot for using tidymodels with augment. We need to create the parsnip templates for the predict method to let tidymodels use the broom methods.

parsnip documentation: https://parsnip.tidymodels.org/reference/set_new_model.html

as well as https://www.tidymodels.org/learn/develop/models/#step-4.-add-modules-for-prediction

**Comment by danielinteractive** [comment]
@yonicd Can you add a reprex of what fails otherwise or how it should work? I guess we need this before 0.3 release, correct?

**Comment by yonicd** [comment]
we need to add to this function https://github.com/openpharma/mmrm/blob/main/R/interop-parsnip.R#L7 a template for what it should expect for the predict method

**Comment by danielinteractive** [comment]
@dgkf would you be interested maybe to add this?
