### ISSUE TITLE
Swapped definition of CR2 and CR3 for vcov in the manual

### ISSUE THREAD

**Issue by Generalized** [openpharma/mmrm#378]
I think the definitions of covariance estimator type are swapped:

> Allowed vcov includes: "Asymptotic", "Kenward-Roger", "Kenward-Roger-Linear", "Empirical" (CR0), "Empirical-Jackknife" (CR2), and "Empirical-Bias-Reduced" (CR3).

CR2 is the bias-reduced (linearization) by Pustejovsky-Tipton,
and CR3 is the leave 1  cluster out (jacknife)

package version: 0.3.5.9002
also in the CRAN version (0.3.6): https://cran.r-project.org/web/packages/mmrm/mmrm.pdf

**Comment by clarkliming** [comment]
thank you @Generalized . indeed in the this doc they are swapped. In the vignettes it is ok
