### ISSUE TITLE
mmrm bioconductor dependancy

### ISSUE THREAD

**Issue by statasaurus** [openpharma/mmrm#418]
When trying to install {mmrm} with {renv} it thinks it needs bioconductor. We think this might be because of the biocViews field in the description. (see image below about renv output) 

<img width="554" alt="image" src="https://github.com/openpharma/mmrm/assets/55274484/65f1c1a1-effc-47a7-affc-3f803d06c9f3">

**Comment by danielinteractive** [comment]
@yonicd I think you could track this down to a known `renv` issue right?

**Comment by yonicd** [comment]
This issue https://github.com/rstudio/renv/issues/1356 seems to have a similar throughline.

**Comment by andyofsmeg** [comment]
This is (at least) renv version 1.0.0.

**Comment by danielinteractive** [comment]
Could this be just because of https://github.com/openpharma/mmrm/blob/main/DESCRIPTION#L93 ?
