### ISSUE TITLE
Please help on the Error message below

### ISSUE THREAD

**Issue by studentxinwq** [openpharma/mmrm#449]
**Summary**

Your brief description of the problem

```r

# your reproducible example here

```

**R session info**

```sh

# R -e "utils::sessionInfo()" output goes here

```

**OS / Environment**

- OS: [e.g. Windows 10, Ubuntu 20.04, Centos 8]
- Docker Image [e.g. rocker/verse:4.1.0]

**Comment by danielinteractive** [comment]
Hi @studentxinwq , can you please add the content, instead of just posting the template? (I guess that was unintentional)

**Comment by danielinteractive** [comment]
closing because stale
