### ISSUE TITLE
Add an S3 method AICc(object, ...)

### ISSUE THREAD

**Issue by xiaohuagong** [openpharma/mmrm#457]
To do:

- [ ] calculate the Second-order Akaike Information Criterion (Hurvich, C. M. and Tsai, C.-L. 1989)

**Comment by danielinteractive** [comment]
Thanks @xiaohuagong , can you please check whether `AIC(fit, corrected = TRUE)` already implements this? See https://openpharma.github.io/mmrm/latest-tag/reference/mmrm_tmb_methods.html#functions e.g.

**Comment by xiaohuagong** [comment]
@danielinteractive Thanks. We were able to have the corrected AIC values in the outputs.
