### ISSUE TITLE
Request to add feature for transformed residuals

### ISSUE THREAD

**Issue by alex-lauer** [openpharma/mmrm#458]
**Summary**

In order to perform fit diagnostics for MMRMs, I would like to create scatterplots of predicted values versus residuals. The standard `residuals()` function provides residuals defined by

```math
r_i = y_i - X_i\hat\beta\,.
```
These 'naive' residuals are problematic in the context of repeated measurements. The scatterplots of predicted values versus residuals will not necessarily have a constant range, as the variance is not necessarily constant. Additionally, residuals from an MMRM can be correlated with covariates. As a result there may be an apparent systematic trend in the scatterplot of the residuals against a selected covariate.

To tackle these problems, Fitzmaurice et al. suggest the use of transformed residuals, defined by

```math
r_i^* = L_i^{-1}(y_i - X_i\hat\beta)\,,
```
where $`L_i`$ is the lower triangular matrix from the Cholesky decomposition of $`\Sigma_i`$. These transformed residuals now have constant variance and zero correlation and allow for the usual fit diagnostics.

Source: 
Fitzmaurice, Laird, G. M. 2011. _Applied Longitudinal Analysis_. Vol. 2. USA: New York, Wiley. [https://doi.org/10.1002/9781119513469](https://doi.org/10.1002/9781119513469).

Describe the new feature/improvement you would like briefly below:
As the use of naive residuals is rather misleading, I would suggest to add a function `residuals.mmrm()` with transformed residuals to the package. The inverse of the lower triangular matrix from the Cholesky decomposition of the variance-covariance matrix $`\Sigma_i`$ is already used several times, but an extraction from the `mmrm`-object did not seem to be possible.

* Provide examples of real-world use cases that this would enable
and how it solves the problem you described.

This feature would allow for more meaningful fit diagnostics using residuals.

* How do you solve this now?

```r
# Extract the variance-covariance matrix
Sigma <- VarCorr(my_mmrm)
L <- t(chol(Sigma))
L_inv <- solve(L) %*% L

trans_res <- L_inv %*% residuals(my_mmrm)
```

**Additional Information**

I created this issue following a discussion with @kkmann .

**Comment by danielinteractive** [comment]
Thanks @alex-lauer for the feature request, much appreciated.

Can you double check whether the "normalized" residuals (see e.g. https://openpharma.github.io/mmrm/latest-tag/articles/introduction.html?q=residuals#residuals) give this already maybe?

**Comment by alex-lauer** [comment]
Thanks @danielinteractive! This is exactly what I needed. Sorry for missing it in the package documentation. Please let me know if you could use my help for a fit diagnostics vignette/ article. I think this could be valuable.

**Comment by danielinteractive** [comment]
Thanks @alex-lauer - that is what I was hoping 😄 

Yes sure, happy to get another vignette for diagnostics! You can also have a look what we have in `tern.mmrm` in terms of diagnostics functionality, and https://github.com/florianhartig/DHARMa/issues/358 might also help once done.
