### ISSUE TITLE
Equivalency for SLICE Statement from PROC MIXED

### ISSUE THREAD

**Issue by hzhang2-cims** [openpharma/mmrm#465]
**Summary**

Dear development team. Thanks again for the amazing work!!

We are currently working on replicating the SAS results generated by proc mixed using the {mmrm}.

One cause for result discrepancy we noticed, is the [SLICE statement ](https://documentation.sas.com/doc/en/statug/15.2/statug_mixed_syntax15.htm)in proc mixed for a partitioned analysis of the LS-means for an interaction.

In terms of LSM, SE, p-value and CI, {mmrm} compares well with PROC MIXED without the SLICE statement but differ slightly when SLICE statement is used.

It would be fantastic if an equivalent feature for SLICE from proc mixed can be developed in the future.

**Comment by yonicd** [comment]
This sounds like functionality that would be in the `emmeans` package and not treated directly in `mmrm`. you can see an example [here](https://lbelzile.github.io/experimental/example/threewayanova.html#interaction-components)

**Comment by danielinteractive** [comment]
Thanks @hzhang2-cims , can you please give a reproducible example? Best also including some mathematical description what this `slice` statement is intended to do. That would help us to understand better and check on our side.

**Comment by danielinteractive** [comment]
@hzhang2-cims would you like to give an example? Otherwise we will close this as it is stale

**Comment by danielinteractive** [comment]
Closing because stale, please reach out if you would like to give an example
