### ISSUE TITLE
Installation order of TMB and mmrm is critical

### ISSUE THREAD

**Issue by weberse2** [openpharma/mmrm#476]
I upgraded on my R installation first mmrm and then TMB... doing so leads to mmrm not being usable as I get the error message

<img width="377" alt="image" src="https://github.com/user-attachments/assets/45004db3-bff0-4d9a-9a1c-8a4c31d94681">

This is due to a call to tmb config returning something which is NULL rather than well defined (in your R/utils.R file). Simply installing again things in the order of first TMB and then mmrm fixes everything, but that is really not intuitive for users.

To reproduce simply install and oldish mmrm and TMB version. Then upgrade mmrm and then TMB. As a result mmrm is not usable.

**Comment by danielinteractive** [comment]
Thank you @weberse2 for the report!

Interesting. I was pretty confident that https://github.com/openpharma/mmrm/blob/main/R/utils.R#L536 prevents older `TMB` versions to even evaluate the config.

**Comment by clarkliming** [comment]
it can be possible that

1. install the old version of TMB and then latest version of mmrm
2. load the package of TMB and mmrm
3. packageVersion tell you the current TMB is smaller than 1.9.15
4. update TMB package to 1.9.15
5. packageVersion('TMB') returns 1.9.15 once installation is done (packageVersion reads the description of the package and it gets updates after you update the package)
6. however the loaded package, will not be updated (unless you `unloadNamespace('TMB')` manually, of course you need to unload `mmrm` first

**Comment by danielinteractive** [comment]
Thanks @clarkliming , yes for binary package installation this is probably all that could happen.

I wondered @weberse2 whether you experienced this in a source installation, I e. When compiling the packages yourself during installation?

**Comment by weberse2** [comment]
Yes, this happened inside a docker image running linux and I installed from source.

**Comment by danielinteractive** [comment]
@kaskr is there a way for us to query the version of `TMB` which was used to compile `mmrm`? (so not the `TMB` package version loaded)

**Comment by kaskr** [comment]
@danielinteractive There's no version information in the compiled dll/so.
I think I would change to something like

```r
h_tmb_warn_non_deterministic <- function() {
  tmb_config <- TMB::config(DLL = "mmrm")
  tape_deterministic <- tmb_config$tmbad_deterministic_hash
  if (is.null(tape_deterministic) || !tape_deterministic) {
    TMB::config(optimize.instantly=0L, DLL = "mmrm")
    msg <- paste(
      "TMB tape optimizer has been disabled to ensure deterministic results.",
      "Consider reinstalling mmrm from source using TMB version at least 1.9.15",
      sep = "\n"
    )
    warning(msg)
}
```

**Comment by wds15** [comment]
This looks about right to me.
