### ISSUE TITLE
Design a hex sticker for `mmrm`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#57]
To do:

- [x] Have fun!
- [x] Create svg and png versions
- [x] Upload to repo
- [x] Use in README and vignette
	- [x] see https://github.com/insightsengineering/hermes as example for how to do this

**Comment by BrianLang** [comment]
So I've put some up into the document and have noticed that the "for" text 
with just the stroke tends to look a bit weird in the small sizes that we're rendering for the site.

**Home page**
<img width="887" alt="Screenshot 2022-08-19 at 17 54 48" src="https://user-images.githubusercontent.com/5337833/185660305-140c68c6-1382-4bc6-a9ab-a259b2e55dc1.png">

**Article**
<img width="859" alt="Screenshot 2022-08-19 at 18 02 01" src="https://user-images.githubusercontent.com/5337833/185660274-56cb4630-227d-4ac5-9204-b7a1a7951ff9.png">

it may look better without the text for "for".

**Home page**
<img width="889" alt="Screenshot 2022-08-19 at 17 54 23" src="https://user-images.githubusercontent.com/5337833/185660663-a799054b-56e4-4422-85c9-f44ed4cea33d.png">


**Article**
<img width="879" alt="Screenshot 2022-08-19 at 17 54 57" src="https://user-images.githubusercontent.com/5337833/185660580-b1d1a51e-5d33-4acb-bc03-a7d22923f254.png">

What do we think?
@ywang-gilead , @danielinteractive ?

**Comment by ywang-gilead** [comment]
I guess we may need to add some space between "model" and "for". And maybe make "for" even smaller?

**Comment by danielinteractive** [comment]
Hm interesting how about reverting to gray filled font for the for?

**Comment by BrianLang** [comment]
I don't mind this, what do you think?

**home page**
<img width="852" alt="Screenshot 2022-08-19 at 19 52 24" src="https://user-images.githubusercontent.com/5337833/185678549-968fb13c-3e32-4119-89ae-1b0a8d6157d2.png">

**article**
<img width="841" alt="Screenshot 2022-08-19 at 19 52 35" src="https://user-images.githubusercontent.com/5337833/185678558-6fcd5aad-10bd-4894-b4f8-7121bbe16ba7.png">

**Comment by danielinteractive** [comment]
I think it looks great like this !

**Comment by BrianLang** [comment]
Cool! I'll do the PR. Thanks both for your help :-)
