### ISSUE TITLE
Design for Kenward-Roger d.f.

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#63]
Material:

- [x] Start from implementation notes: https://github.com/runehaubo/lmerTestR/blob/master/pkg_notes/implementation.Rmd
- [x] Also look at part here: https://drive.google.com/file/d/1imAEKUPCbSieDMoozXjexkPBsl1YNkcV/view?usp=sharing
- [x] Look at code: https://github.com/runehaubo/lmerTestR/blob/35dc5885205d709cdc395b369b08ca2b7273cb78/R/contest.R#L282
- [x] How does it work together with `pbkrtest`: https://people.math.aau.dk/~sorenh/software/pbkrtest/
- [x] explore autodiff:jacobian in TMB
- [x] explore TMB plus Rcpp integration
- [x] create prototypes of deriving P, Q, R
- [ ] match results with SAS

**Comment by danielinteractive** [comment]
@clarkliming please adjust issue description as you see fit / as you lay out the tasks

**Comment by yonicd** [comment]
i found another implementation of KR derivation in [{parameters}](https://github.com/easystats/parameters/blob/main/R/dof_kenward.R)

**Comment by clarkliming** [comment]
the KR derivation in {parameters} looks identical to the pbkrtest, including comments. I guess they are just copying code from there.
