### ISSUE TITLE
Clean up exports

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#64]
To do:

- [x] decide which objects do not need to be exported
- [x] add appropriate badge experimental, stable, deprecated to all exported objects
- [x] _pkgdown.yaml should only contain exported objects
- [x] unexported objects must have documentation but they need `@keywords internal` tag and must not have examples (since those won't run) 
	- [x] when removing examples from those, please make sure that the same thing is covered in existing unit tests, or otherwise add the example as a new unit test - so that we don't lose covering that case basically.
- [x] Use this script to easily detect what is left to do. 
```
#' packages having keyword internal and matching specific type
rd_index_installed <- function(pkg, type = NULL) {
  db <- tools::Rd_db(pkg)
  elo <- tools:::.build_Rd_index(tools:::Rd_contents(db), type = type)
  elo$Name
}

man_files <- function(path) {
  list.files(file.path(path, "man"), full.names = TRUE, pattern = ".Rd")
}

rd_index <- function(path = ".") {
  all_docs <- man_files(path)
  res <- vapply(all_docs, FUN.VALUE = logical(1), FUN = function(x) {
    lines <- readLines(x)
    any(grepl("keyword\\{.*internal\\}", lines))
  })
 sort(gsub(".Rd$", "", basename(names(res[!res]))))
}

badge <- function(path = ".") {
  all_docs <- man_files(path)
  res <- vapply(all_docs, FUN.VALUE = logical(1), FUN = function(x) {
    lines <- readLines(x)
    any(grepl("figure\\{lifecycle", lines))
  })
  sort(gsub(".Rd$", "", basename(names(res[res]))))
}


path <- "."
pkg <- "mmrm"


# has a badge but it's internal
setdiff(badge(path), rd_index(path))

# is in documentation index but has no badge
setdiff(rd_index(path), badge(path))

# unexported functions in the doc index
setdiff(rd_index(path), sort(getNamespaceExports(pkg)))
setdiff(rd_index_installed(pkg), sort(getNamespaceExports(pkg)))

```

**Comment by danielinteractive** [comment]
Thanks @BrianLang for starting on this one!

Yeah agree there are much fewer things to export than not. I agree with your list so far!

For the others:
- tmb: I would also export `h_mmrm_tmb_control()` such that the user who uses `h_mmrm_tmb()` directly can manage those settings
- fitting routines: I think it is sufficient to only export `mmrm()`
- parallel: I would export `h_free_cores()` since it is called in `tern.mmrm` downstream directly
- Satterthwaite stuff: I would export `df_1d()` and `df_md()` (because it is nice to be able to do this without extra packages if wanted)

**Comment by danielinteractive** [comment]
btw I think we can't and don't need to export the example data set. with the lazy data loading it is available to the user. 

btw 2: see also recent https://github.com/insightsengineering/tern.mmrm/pull/87 which was cleaning up `tern.mmrm` in a similar way.

**Comment by BrianLang** [comment]
Great feedback, thanks! Forgot that one with 'control()'

**Comment by BrianLang** [comment]
Would like some feedback:

1. on how we choose badges.  Right now everything is still external.
2. on if we really get rid of all mention of non-exported functions from the _pkgdown. as it is now, they are separated into "helper functions" and "functions". 
3. `refit_multiple_optimizers` and `fit_single_optimizer` are both in the `_pkgdown.yml` as functions, but I've just removed them from exports. are we still in favor of having them internal? 

Thanks!

**Comment by danielinteractive** [comment]
Thanks @BrianLang !

- Badges: yes that is right since this is the first package version let's have everything as `experimental`. In next version we can then upgrade to stable
- Yeah let's get rid of internal functions in pkgdown
- OK let's keep these two additional fitting functions exported
