### ISSUE TITLE
Design for Type II and Type III tests a la `car::Anova()`

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#67]
To do: 
- [x] Read `?car::Anova`
- [x] Go through code material:
	- [x] `glmmTMB` implementation: https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/Anova.R
	- [x] `car` package code: https://github.com/cran/car/tree/master/R
- [x] Write a design doc first (so no production package code yet)
    - [x] strategy (and several options for it if it makes sense)
	- [x] prototype code

Note (from `?car::Anova?` Details): 
The designations "type-II" and "type-III" are borrowed from SAS, but the definitions used here do not correspond precisely to those employed by SAS. 
- Type-II tests are calculated according to the principle of marginality, testing each term after all others, except ignoring the term's higher-order relatives; This definition of Type-II tests corresponds to the tests produced by SAS for analysis-of-variance models, where all of the predictors are factors, but not more generally (i.e., when there are quantitative predictors).
- so-called type-III tests violate marginality, testing each term in the model after all of the others.  Be very careful in formulating the model for type-III tests, or the hypotheses tested will not make sense.

**Comment by erinwillia** [comment]
Hello!

I am using your mmrm package to do some exploratory analyses and was wondering if, upon model selection/generation, you had implemented some way to do ANOVA-type analyses between variables to generate an F-statistic?

I see here that it was on the to-do list, but perhaps there is an update I am missing?  If not, do you have any thoughts on how to acquire the F-statistic using mmrm manually?

Thank you for great package — I am delighted not to use SAS!

**Comment by erinwillia** [comment]
Hi @danielinteractive !  Thank you for your reply. 

Just one more question, and please forgive my ignorance...

What are the numbers in 2nd line referring to?  I understand that the first line is calling our matrix?

contrast <- matrix(data = 0, nrow = 2, ncol = length(object$beta_est))
contrast[1, 2] <- contrast[2, 3] <- 1

**Comment by danielinteractive** [comment]
Sure, we should explain this a bit better in the vignette I think. Basically in the first line we set up an empty (all zeros) matrix with 2 rows and p columns (where p is the dimension of the coefficients vector beta). Then in the second line we just set the elements (1,2) and (2,3) to 1. This means we are testing the hypothesis that the second and the third coefficient are zero by the F test.

**Comment by erinwillia** [comment]
And if we had more coefficients, say 8 total?  How would this change our line of code?

**Comment by danielinteractive** [comment]
Analogously, basically you create a matrix where you have the 1s at the coefficients you want to test vs zero. But we will improve the vignette to clarify it

**Comment by Generalized** [comment]
I'm wondering how this relates to emmeans::joint_tests(), which gives multivariate Wald's testing (F or chi2 statistic), for the LM theoretically equivalent to LRT testing - effectively the F test (reduction in variance = reduction in deviance for the GLM, which the LM is special kind of).

I use the example from mmrm site: https://openpharma.github.io/mmrm/latest-tag/reference/df_md.html

Let's first fit the model:
```{r}
object <- mmrm(
    formula = FEV1 ~ RACE + SEX + ARMCD * AVISIT + us(AVISIT | USUBJID),
    data = fev_data
)
```
Let's focus on two races: white and black. Using the model coefficients, RACE is assessed with respect to the intercept, 
which stands for: VIS1, PBO and Male. Let's calculate the group adjusted mean for these

```{r}
round(c(coef(object)[1:3][1], sum(coef(object)[1:3][1:2]), sum(coef(object)[1:3][c(1,3)])), 5)
(Intercept)                         
   30.77748    32.30798    36.42104 
```

and find the corresponding entries in the emmeans table:
```{r}
(data.frame(em <- emmeans(object, specs = ~ RACE + SEX + ARMCD * AVISIT))[1:3,])
                       RACE  SEX ARMCD AVISIT   emmean        SE       df lower.CL upper.CL
1                     Asian Male   PBO   VIS1 30.77748 0.8865648 218.8018 29.03018 32.52478
2 Black or African American Male   PBO   VIS1 32.30798 0.8506127 204.4131 30.63088 33.98507
3                     White Male   PBO   VIS1 36.42104 0.9353129 247.8654 34.57887 38.26322
```
which agrees with the means obtained directly from the coefficients:
```{r}

So now let's test two coefficients (= corresponding means) for black and white race jointly.

Method from the example:
```{r}
> contrast <- matrix(data = 0, nrow = 2, ncol = length(object$beta_est))
> contrast[1, 2] <- contrast[2, 3] <- 1
> df_md(object, contrast)
$num_df
[1] 2

$denom_df
[1] 165.5553

$f_stat
[1] 36.91143

$p_val
[1] 5.544575e-14
```

and from emmeans:
```{r}
> em %>% contrast(list(WHITE_V1_PBO_Male = c(0, 0, 1, rep(0, 45)),
+                      BLACK_V1_PBO_Male = c(0, 1, 0, rep(0, 45)))) %>% 
+                   test(joint = TRUE, verbose = TRUE)
Joint test of the following linear predictions
           contrast equals
1 WHITE_V1_PBO_Male      0
2 BLACK_V1_PBO_Male      0
 df1    df2 F.ratio p.value
   2 247.87 866.309  <.0001
```
The DoF are now really big, and the F.ratio if huge. When I took square root, it was closer to the previously obtained value:
```{r}
> sqrt(866.309)
[1] 29.43313

#vs.
$f_stat
[1] 36.91143
```
I'm wondering what causes it.

OK, let's check just a single coefficient:

```{r}
> contrast <- matrix(data = 0, nrow = 1, ncol = length(object$beta_est))
> contrast[1, 2] <- 1
> contrast
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    0    1    0    0    0    0    0    0    0     0     0

> df_md(object, contrast)
$num_df
[1] 1

$denom_df
[1] 168.6657

$f_stat
[1] 6.0067

$p_val
[1] 0.01527218
```

vs.
```{r}
> em %>% contrast(list(BLACK_V1_PBO_Male = c(0, 1, 0, rep(0, 45))))
 contrast         estimate    SE  df t.ratio p.value
 BLACK_V1_PBO_Male     32.3 0.851 204  37.982  <.0001
```
Well, not quite...
Again, t.ratio = 37.982 , but if I take the sqrt(37.982 ) = sqrt(37.982 ) = 6.162954 which now matches the example.

Also let's do the overall type-3 testing:
```{r}
> joint_tests(object)
model term   df1    df2 F.ratio p.value
RACE           2 157.14  36.911  <.0001
SEX            1 166.13   0.376  0.5407
ARMCD          1 168.52  31.663  <.0001
AVISIT         3 129.70 142.112  <.0001
ARMCD:AVISIT   3 129.72   0.258  0.8555
```

**Comment by Generalized** [comment]
@danielinteractive 

Let's not forget also about the `emmeans::joint_tests()`, which gives uni/multivariate Wald's testing (F or chi2 statistic) of contrasts.
/ For the general linear models, resulting in quadratically-shaped (ideally) log-likelihood curve, Wald's approach is theoretically equivalent to Wilks' LRT, where the F tests reduction in residual variance (deviance for the GLM, which the LM is special kind of). Using Satterthwaite and K-R DoF improves the small-size problems with Wald's. /

I'm gonna use the example from mmrm site: https://openpharma.github.io/mmrm/latest-tag/reference/df_md.html

Let's first fit the model:
```{r}
object <- mmrm(
    formula = FEV1 ~ RACE + SEX + ARMCD * AVISIT + us(AVISIT | USUBJID),
    data = fev_data
)

```
Let's focus on two races: white and black. Using the model coefficients, RACE is assessed with respect to the intercept, 
which stands for: VIS1, PBO and Male. Let's calculate the group adjusted means for the three races:

```{r}
round(c(coef(object)[1:3][1], sum(coef(object)[1:3][1:2]), sum(coef(object)[1:3][c(1,3)])), 5)
(Intercept)                         
   30.77748    32.30798    36.42104 
```

and find the corresponding entries in the emmeans table:
```{r}
(data.frame(em <- emmeans(object, specs = ~ RACE + SEX + ARMCD * AVISIT))[1:3,])
                       RACE  SEX ARMCD AVISIT   emmean        SE       df lower.CL upper.CL
1                     Asian Male   PBO   VIS1 30.77748 0.8865648 218.8018 29.03018 32.52478
2 Black or African American Male   PBO   VIS1 32.30798 0.8506127 204.4131 30.63088 33.98507
3                     White Male   PBO   VIS1 36.42104 0.9353129 247.8654 34.57887 38.26322
```
which agrees with the means obtained directly from the coefficients:

Now let's test two coefficients for black and white race jointly. The only issue is that:
- for the coefficient-based testing, meaning of contrasts depends on coding (treatment, effect/sum), and for the treatment-coding only intercept represents a (reference) mean, all other coefficients stand for shifts from it.

- for the LS-mean-based testing, meaning of contrasts is fixed. So if we want to translate between the two we need to be careful.

Method from the example - tests jointly shifts from the ASIAN race.

```{r}
> contrast <- matrix(data = 0, nrow = 2, ncol = length(object$beta_est))
> contrast[1, 2] <- contrast[2, 3] <- 1
> df_md(object, contrast)
$num_df
[1] 2

$denom_df
[1] 165.5553

$f_stat
[1] 36.91143

$p_val
[1] 5.544575e-14
```

By employing the emmeans, we need to define the shift contrasts
```{r}
em %>% 
  contrast(list(ASIAN_WHITE_V1_PBO_Male = c(-1, 0, 1, rep(0, 45)),
                ASIAN_BLACK_V1_PBO_Male = c(-1, 1, 0, rep(0, 45)))) %>% 
                     test(joint = TRUE, verbose = TRUE)

Joint test of the following linear predictions
                 contrast equals
1 ASIAN_WHITE_V1_PBO_Male      0
2 ASIAN_BLACK_V1_PBO_Male      0
 df1    df2 F.ratio p.value
   2 157.14  36.911  <.0001
```
The DoF are a bit different, and I'm wondering why. The F statistic agrees. 

For a single difference the DoF agree well:
```{r}
contrast <- matrix(data = 0, nrow = 1, ncol = length(object$beta_est))
contrast[1, 1:2] <- 1
contrast
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,]    1    1    0    0    0    0    0    0    0     0     0
df_md(object, contrast)
$num_df
[1] 1

$denom_df
[1] 204.4131

$f_stat
[1] 1442.633

$p_val
[1] 1.430127e-94

# Let's take the square root of F to obtain t:
sqrt(1442.633)
[1] 37.98201

# vs emmeans:

em %>% contrast(list(ASIAN_BLACK_V1_PBO_Male = c(0, 1, 0, rep(0, 45))))
 contrast         estimate    SE  df t.ratio p.value
 ASIAN_BLACK_V1_PBO_Male     32.3 0.851 204  37.982  <.0001
```
Perfect.

Just the last thing - the type-3 Wald's testing. One only needs to remember, that for numerical covariates it uses DIFFERENT reference. SAS and R by default take 0, which is rarely of interest. Emmeans takes the mean value of the numerical covariate, but this behavior can be altered, making it closer to SAS.

```{r}
> joint_tests(object)
model term   df1    df2 F.ratio p.value
RACE           2 157.14  36.911  <.0001
SEX            1 166.13   0.376  0.5407
ARMCD          1 168.52  31.663  <.0001
AVISIT         3 129.70 142.112  <.0001
ARMCD:AVISIT   3 129.72   0.258  0.8555
```

PS: if one prefers to use ls-means in place of model coefficients, this code (not mine) facilitates it a lot:
```{r}
d <- fev_data %>% filter(complete.cases(.))

group <- paste0(d$RACE, d$SEX, d$ARMCD, d$AVISIT) # no empty data!
group <- aggregate(model.matrix(object,data = fev_data) ~ group, FUN=mean)
rownames(group) <- group$group
(group <- group[,-1])
```
![obraz](https://github.com/openpharma/mmrm/assets/60151643/08df1e9f-3e6e-4283-8bb6-c8a1734032a5)


Then, contrasts and contrasts-of-contrasts (just differences of vectors/matrices) can be tested e.g. via multcomp::glht, car::linearHypothesis or glmglrt::p_value_contrast (only if we use the GLS rather than MMRM... But maybe you could contact the author and provide appropriate bridging?)

**Comment by clarkliming** [comment]
thank you for your reply. we are still reading relevant materials to help us decide on the implementations of type II/III ANOVA. Curreently it seems that emmans::joint_test is what we should follow.

https://github.com/rvlenth/emmeans/issues/211

**Comment by clarkliming** [comment]
and maybe using joint test is a better choices than using ancova (might be hard to inteprete)

https://stats.stackexchange.com/questions/60362/choice-between-type-i-type-ii-or-type-iii-anova

**Comment by danielinteractive** [comment]
Trying to find papers supporting the type II and type III methods.
@chstock do you maybe have any leads on that? Basically where the method details of these are defined? (and in particular what SAS is using)

**Comment by chstock** [comment]
> Trying to find papers supporting the type II and type III methods. @chstock do you maybe have any leads on that? Basically where the method details of these are defined? (and in particular what SAS is using)

@danielinteractive, sorry, I have seen this just now. Will have a look!

**Comment by clarkliming** [comment]
Hi @chstock the paper can be found in the comment above

> see paper here
> https://doi.org/10.1080/03610928008827869
> A more recent doc https://support.sas.com/documentation/onlinedoc/stat/131/introglmest.pdf

**Comment by danielinteractive** [comment]
Thanks @chstock , and the design doc has been merged now here: https://github.com/openpharma/mmrm/tree/main/design/anova
