### ISSUE TITLE
Add homogeneous ante-dependence covariance structure

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#81]
To do:

- [x] Add definition of homogeneous ante-dependence covariance structure to covariance vignette 
  - [x] merge it together with heterogeneous ante-dependence covariance we already have
  - [x] rename heterogeneous to `adh` and keep the homogeneous as `ad`- carry this through below
- [x] Adjust covariance structure choices in https://github.com/openpharma/mmrm/blob/709f392e966b12514525ea6f6118d8e9af32089c/R/tmb.R#L60
- [x] Initialize start parameters in https://github.com/openpharma/mmrm/blob/709f392e966b12514525ea6f6118d8e9af32089c/R/tmb.R#L208
	- [x] Amend tests in https://github.com/openpharma/mmrm/blob/709f392e966b12514525ea6f6118d8e9af32089c/tests/testthat/test-tmb.R#L80
- [x] Amend printing of covariance structure in https://github.com/openpharma/mmrm/blob/b1b612263623c9d8f9e972adf19d09e23558664c/R/mmrm-methods.R#L109
- [x] Add lower Cholesky factor function and include it in branching in 
https://github.com/openpharma/mmrm/blob/01ae7f936cd43ad8788b84a7a03467b217a9ccaa/src/covariance.h#L41
	- [x] do it similar as with the autoregressive covariance structure where we also have homogeneous and heterogeneous
	- [x] Test it in https://github.com/openpharma/mmrm/blob/main/src/test-covariance.cpp
		- [x] Install and Restart package
		- [x] Build > More > Test package
- [x] Amend integration tests in https://github.com/openpharma/mmrm/blob/709f392e966b12514525ea6f6118d8e9af32089c/tests/testthat/test-tmb.R#L256
	- [x] Note that `r2stream` is not available outside of Roche, so just run SAS differently and save log as text file in the design folder as reference --> change to use mmrm results for testing since homegeneous ad cov is not available in SAS
- [x] Run Clean and Rebuild > Check to ensure that checks pass

**Comment by danielinteractive** [comment]
@ywang-gilead feel free to assign to yourself if you have time to work on it :-) otherwise can leave here in todo's until you or somebody else has time

**Comment by ywang-gilead** [comment]
> @ywang-gilead feel free to assign to yourself if you have time to work on it :-) otherwise can leave here in todo's until you or somebody else has time
@danielinteractive just assigned to myself and I'm working on it today

**Comment by ywang-gilead** [comment]
SAS does not have homogeneous ante-dependence covariance structure

do we want to amend tests in https://github.com/openpharma/mmrm/blob/7fb8e4718a03b340fcc08118e0cb798ec9d252fc/tests/testthat/test-cpp-covariance.R#L1?

**Comment by danielinteractive** [comment]
Good question! 
- Does SAS maybe have another name for it? Or maybe there is a way to have a parameter to force equal variances?
- Otherwise there might be no direct way to compare, in that case that is ok as well and I would just record the results you currently obtain as test expectations

**Comment by danielinteractive** [comment]
Yea please also amend C++ tests like we did before

**Comment by ywang-gilead** [comment]
I checked the SAS documentation (https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.3/statug/statug_mixed_syntax14.htm) but couldn't find it. I haven't found a way to force equal variances from the documentation, but I'll double check.

**Comment by danielinteractive** [comment]
Thanks Ya, otherwise is fine as well, I am confident that our results will be correct
