### ISSUE TITLE
Add possibility to set `weights` to obtain weighted MMRM

### ISSUE THREAD

**Issue by danielinteractive** [openpharma/mmrm#84]
To do:

- [x] Amend algorithm vignette to understand how the weights would be included in the fitting process
- [x] Add argument to `mmrm()` and related functions (to be detailed here)
	- [x] Add argument to `mmrm()` and `fit_single_optimizer()` in file `R/fit.R`
    - [x] Add argument to `h_mmrm_tmb` and `h_mmrm_tmb_data` in file `R/tmb.R`
    - [x] Update file `/src/mmrm.cpp`
- [x] For lower level functions: Add unit tests for the weights functionality for all functions which are involved
- [x] For `mmrm()`: Add integration test where we compare results with SAS results
	- [x] seems ok for weights = 1 (no weights)
	- [x] resolve differences for random weights
	- [x] including d.f.
- [x] For `print()` method: It would be good if we could include a line that mentions the weights there
	- [x] e.g. in here: https://github.com/openpharma/mmrm/blob/97373f29793a4b04563b91a91f3c4482807a9c6d/R/tmb-methods.R#L185
	- [x] can maybe do same trick as here: https://github.com/openpharma/mmrm/blob/97373f29793a4b04563b91a91f3c4482807a9c6d/R/fit.R#L220
- [x] Document in the introduction vignette

**Comment by clarkliming** [comment]
https://github.com/kaskr/adcomp/wiki/Things-you-should-NOT-do-in-TMB

I happen to read this page: do not implement weighting in c++ side. is this relevant to this issue?

**Comment by danielinteractive** [comment]
@clarkliming no, not relevant here because we don't do any Laplace approximation, we are also not weighting the log-likelihood directly, so all good.
