### ISSUE TITLE
refactor: code readability + package structure

### ISSUE THREAD

**Issue by kkmann** [openpharma/mmrm#98]
Hey,

sorry that my first issue is not at all about extending the functionality of mmrm. I am proposing to refactor the code basis a bit to be closer to the tidyverse way of structuring a package. I would hope that this makes it easier to understand the code base and maybe also to contribute. As with all things related to taste, there is no right or wrong here :)

Key issues that I personally stumbled upon: 

- [ ] file names do not correspond to content, e.g. `satterthwaite.R` -> `df_md()`
- [ ] main functions defined at end of files (also `satterthwaite.R`) and start with detailed h_* functions
- [ ] reduce exported functions further - see https://github.com/openpharma/mmrm/blob/692ad6b0441056eece083a015a14296a2bde67ba/NAMESPACE#L16 for starting point
- [ ] h_* pattern is not really necessary (use @export, everything that's not exported is a helper); leads to bloated code and (if not explained) confusion --> we can try with a simple PR that really just substitutes "h_" with nothing and then see how it looks like
- [x] generic utility/helper function not related to package logic could go in `utils.R` to reduce the number of files and make it easier to figure out how the overall structure of the relevant package logic works (`output.R`)

Will start opening PRs with concrete suggestions, let's see whether you agree. Opinions welcome!

**Comment by kkmann** [comment]
related: can someone explain how 

https://github.com/openpharma/mmrm/blob/b45fa724b5ace95d91cfee52edce517427939472/R/catch-routine-registration.R#L1-L8

works and what it is for? It seem to somehow be related to package skeletons but I was not able to figure it out. 

A candidate to be moved to utils.R as well...

**Comment by kkmann** [comment]
currently 

https://github.com/openpharma/mmrm/blob/b45fa724b5ace95d91cfee52edce517427939472/R/fit.R#L23

is exported. 

My preference would be to stick with `mmrm()` as user-facing function (there is always `mmrm:::fit_single_optimizer)`) 

If there is a good use case for it, maybe rename to `fit_mmrm()`? 
a) I would favor no suffix names for the base case (i.e. if any have a `fit_multiple_optimizers`)
b) exporting a generic name as fit_* without the specific model or package name can lead to name space confusion (granted, low probability due to the _single_optimizer suffix, but still)

**Comment by danielinteractive** [comment]
> related: can someone explain how
> 
> https://github.com/openpharma/mmrm/blob/b45fa724b5ace95d91cfee52edce517427939472/R/catch-routine-registration.R#L1-L8
> 
> works and what it is for? It seem to somehow be related to package skeletons but I was not able to figure it out.
> 
> A candidate to be moved to utils.R as well or mmrm-package.R ...

please leave this as is - it is automatically generated, please see https://testthat.r-lib.org/reference/use_catch.html for background

**Comment by danielinteractive** [comment]
> currently
> 
> https://github.com/openpharma/mmrm/blob/b45fa724b5ace95d91cfee52edce517427939472/R/fit.R#L23
> 
> is exported.
> 
> My preference would be to stick with `mmrm()` as user-facing function (there is always `mmrm:::fit_single_optimizer)`)
> 
> If there is a good use case for it, maybe rename to `fit_mmrm()`? a) I would favor no suffix names for the base case (i.e. if any have a `fit_multiple_optimizers`) b) exporting a generic name as fit_* without the specific model or package name can lead to name space confusion (granted, low probability due to the _single_optimizer suffix, but still)

re: export - yeah ok we can try to reduce further. please then in the PR adjust pkgdown / intro vignette etc. when removing exports.

re: naming - I am open to renaming, for sure can be improved

**Comment by danielinteractive** [comment]
@kkmann we just discussed a bit about the `h_*` prefix and there are different opinions about it, so let's discuss at an upcoming standup before working a lot on it :-)

**Comment by kkmann** [comment]
yes, happy to continue. will only get to it next week though.

**Comment by kkmann** [comment]
closing this and following up individually
